// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/database.proto

package core

import (
	postgres "github.com/uthereal/scheme/genproto/postgres"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Database represents a single logical database instance within the Scheme.
// It acts as a top-level container, providing a generic configuration wrapper
// before routing down into engine-specific definitions (e.g., PostgreSQL, MySQL).
type Database struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique, logical name for the database instance.
	// This name is primarily used by the framework to construct isolated
	// generated packages (e.g., 'package mydb') and configuration bindings.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The engine-specific database configuration and schema hierarchy.
	//
	// Types that are valid to be assigned to Engine:
	//
	//	*Database_Postgres
	Engine        isDatabase_Engine `protobuf_oneof:"engine"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_core_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_core_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_core_database_proto_rawDescGZIP(), []int{0}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Database) GetEngine() isDatabase_Engine {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *Database) GetPostgres() *postgres.PostgresDatabase {
	if x != nil {
		if x, ok := x.Engine.(*Database_Postgres); ok {
			return x.Postgres
		}
	}
	return nil
}

type isDatabase_Engine interface {
	isDatabase_Engine()
}

type Database_Postgres struct {
	// The complete schema layout and configuration for a PostgreSQL database.
	Postgres *postgres.PostgresDatabase `protobuf:"bytes,2,opt,name=postgres,proto3,oneof"`
}

func (*Database_Postgres) isDatabase_Engine() {}

var File_core_database_proto protoreflect.FileDescriptor

const file_core_database_proto_rawDesc = "" +
	"\n" +
	"\x13core/database.proto\x12\x04core\x1a\x17postgres/database.proto\"b\n" +
	"\bDatabase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\bpostgres\x18\x02 \x01(\v2\x1a.postgres.PostgresDatabaseH\x00R\bpostgresB\b\n" +
	"\x06engineBs\n" +
	"\bcom.coreB\rDatabaseProtoP\x01Z(github.com/uthereal/scheme/genproto/core\xa2\x02\x03CXX\xaa\x02\x04Core\xca\x02\x04Core\xe2\x02\x10Core\\GPBMetadata\xea\x02\x04Coreb\x06proto3"

var (
	file_core_database_proto_rawDescOnce sync.Once
	file_core_database_proto_rawDescData []byte
)

func file_core_database_proto_rawDescGZIP() []byte {
	file_core_database_proto_rawDescOnce.Do(func() {
		file_core_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_database_proto_rawDesc), len(file_core_database_proto_rawDesc)))
	})
	return file_core_database_proto_rawDescData
}

var file_core_database_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_database_proto_goTypes = []any{
	(*Database)(nil),                  // 0: core.Database
	(*postgres.PostgresDatabase)(nil), // 1: postgres.PostgresDatabase
}
var file_core_database_proto_depIdxs = []int32{
	1, // 0: core.Database.postgres:type_name -> postgres.PostgresDatabase
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_database_proto_init() }
func file_core_database_proto_init() {
	if File_core_database_proto != nil {
		return
	}
	file_core_database_proto_msgTypes[0].OneofWrappers = []any{
		(*Database_Postgres)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_database_proto_rawDesc), len(file_core_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_database_proto_goTypes,
		DependencyIndexes: file_core_database_proto_depIdxs,
		MessageInfos:      file_core_database_proto_msgTypes,
	}.Build()
	File_core_database_proto = out.File
	file_core_database_proto_goTypes = nil
	file_core_database_proto_depIdxs = nil
}
