// Code generated by the scheme compiler. DO NOT EDIT.
package postgres

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
)

type LogLevel string

const (
	INFO  LogLevel = "INFO"
	ERROR LogLevel = "ERROR"
)

type UserStatus string

const (
	ACTIVE   UserStatus = "ACTIVE"
	INACTIVE UserStatus = "INACTIVE"
	BANNED   UserStatus = "BANNED"
)

type EmailAddress string

type IPAddress string

type Address struct {
	Street *string
	City   *string
	Zip    *string
}

type GeoLocation struct {
	Lat *float32
	Lon *float32
}

type DisposableTable struct {
	ID  int32
	Val string
}

type Post struct {
	ID        int64
	AuthorID  uuid.UUID
	Title     string
	Body      *string
	Views     int64
	PostsUser *User
	Author    *User
	PostTags  []*PostTag
}

type PostTag struct {
	PostID       int64
	TagID        int32
	PostTagsPost *Post
	Metrics      []*PostTagMetric
}

type PostTagMetric struct {
	PostID         int64
	TagID          int32
	MetricName     string
	Value          int32
	MetricsPostTag *PostTag
}

type Tag struct {
	ID   int32
	Name string
}

type TemporaryLog struct {
	ID       uuid.UUID
	Level    LogLevel
	SourceIP IPAddress
	Location GeoLocation
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          EmailAddress
	Status         UserStatus
	BillingAddress *Address
	Age            *int32
	Metadata       json.RawMessage
	CreatedAt      time.Time
	Posts          []*Post
	AuthorPosts    []*Post
}
