// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: go_language.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GoLanguage represents language-specific configuration options for the Go
// generator.
type GoLanguage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The base Go package path for the generated code
	// (e.g., 'github.com/myorg/gen').
	PackagePath   string `protobuf:"bytes,1,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoLanguage) Reset() {
	*x = GoLanguage{}
	mi := &file_go_language_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoLanguage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoLanguage) ProtoMessage() {}

func (x *GoLanguage) ProtoReflect() protoreflect.Message {
	mi := &file_go_language_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoLanguage.ProtoReflect.Descriptor instead.
func (*GoLanguage) Descriptor() ([]byte, []int) {
	return file_go_language_proto_rawDescGZIP(), []int{0}
}

func (x *GoLanguage) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

var File_go_language_proto protoreflect.FileDescriptor

const file_go_language_proto_rawDesc = "" +
	"\n" +
	"\x11go_language.proto\x12\x06scheme\"/\n" +
	"\n" +
	"GoLanguage\x12!\n" +
	"\fpackage_path\x18\x01 \x01(\tR\vpackagePathBz\n" +
	"\n" +
	"com.schemeB\x0fGoLanguageProtoP\x01Z#github.com/uthereal/scheme/genproto\xa2\x02\x03SXX\xaa\x02\x06Scheme\xca\x02\x06Scheme\xe2\x02\x12Scheme\\GPBMetadata\xea\x02\x06Schemeb\x06proto3"

var (
	file_go_language_proto_rawDescOnce sync.Once
	file_go_language_proto_rawDescData []byte
)

func file_go_language_proto_rawDescGZIP() []byte {
	file_go_language_proto_rawDescOnce.Do(func() {
		file_go_language_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_language_proto_rawDesc), len(file_go_language_proto_rawDesc)))
	})
	return file_go_language_proto_rawDescData
}

var file_go_language_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_go_language_proto_goTypes = []any{
	(*GoLanguage)(nil), // 0: scheme.GoLanguage
}
var file_go_language_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_language_proto_init() }
func file_go_language_proto_init() {
	if File_go_language_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_language_proto_rawDesc), len(file_go_language_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_language_proto_goTypes,
		DependencyIndexes: file_go_language_proto_depIdxs,
		MessageInfos:      file_go_language_proto_msgTypes,
	}.Build()
	File_go_language_proto = out.File
	file_go_language_proto_goTypes = nil
	file_go_language_proto_depIdxs = nil
}
