// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scheme.proto

package genproto

import (
	core "github.com/uthereal/scheme/genproto/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scheme acts as the absolute root definition for your application's data
// infrastructure. A single Scheme file can configure a database
// cluster, schemas, tables, cross-database linkages, and relationships.
type Scheme struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A single logically isolated database tracked within the Scheme.
	Database *core.Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Language-specific configuration options for Go.
	Go            *GoLanguage `protobuf:"bytes,2,opt,name=go,proto3" json:"go,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scheme) Reset() {
	*x = Scheme{}
	mi := &file_scheme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scheme) ProtoMessage() {}

func (x *Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_scheme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scheme.ProtoReflect.Descriptor instead.
func (*Scheme) Descriptor() ([]byte, []int) {
	return file_scheme_proto_rawDescGZIP(), []int{0}
}

func (x *Scheme) GetDatabase() *core.Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Scheme) GetGo() *GoLanguage {
	if x != nil {
		return x.Go
	}
	return nil
}

var File_scheme_proto protoreflect.FileDescriptor

const file_scheme_proto_rawDesc = "" +
	"\n" +
	"\fscheme.proto\x12\x06scheme\x1a\x13core/database.proto\x1a\x11go_language.proto\"X\n" +
	"\x06Scheme\x12*\n" +
	"\bdatabase\x18\x01 \x01(\v2\x0e.core.DatabaseR\bdatabase\x12\"\n" +
	"\x02go\x18\x02 \x01(\v2\x12.scheme.GoLanguageR\x02goBv\n" +
	"\n" +
	"com.schemeB\vSchemeProtoP\x01Z#github.com/uthereal/scheme/genproto\xa2\x02\x03SXX\xaa\x02\x06Scheme\xca\x02\x06Scheme\xe2\x02\x12Scheme\\GPBMetadata\xea\x02\x06Schemeb\x06proto3"

var (
	file_scheme_proto_rawDescOnce sync.Once
	file_scheme_proto_rawDescData []byte
)

func file_scheme_proto_rawDescGZIP() []byte {
	file_scheme_proto_rawDescOnce.Do(func() {
		file_scheme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheme_proto_rawDesc), len(file_scheme_proto_rawDesc)))
	})
	return file_scheme_proto_rawDescData
}

var file_scheme_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scheme_proto_goTypes = []any{
	(*Scheme)(nil),        // 0: scheme.Scheme
	(*core.Database)(nil), // 1: core.Database
	(*GoLanguage)(nil),    // 2: scheme.GoLanguage
}
var file_scheme_proto_depIdxs = []int32{
	1, // 0: scheme.Scheme.database:type_name -> core.Database
	2, // 1: scheme.Scheme.go:type_name -> scheme.GoLanguage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scheme_proto_init() }
func file_scheme_proto_init() {
	if File_scheme_proto != nil {
		return
	}
	file_go_language_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheme_proto_rawDesc), len(file_scheme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scheme_proto_goTypes,
		DependencyIndexes: file_scheme_proto_depIdxs,
		MessageInfos:      file_scheme_proto_msgTypes,
	}.Build()
	File_scheme_proto = out.File
	file_scheme_proto_goTypes = nil
	file_scheme_proto_depIdxs = nil
}
