// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/shared/auto_increment.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AutoIncrement defines the sequence parameters for an auto-incrementing column
// (e.g., GENERATED AS IDENTITY in PostgreSQL or AUTO_INCREMENT in MySQL).
type AutoIncrement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The minimum value the sequence can generate.
	Min *int64 `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	// The maximum value the sequence can generate.
	Max *int64 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	// The interval to add to the current sequence value to generate the next value.
	Step *int64 `protobuf:"varint,3,opt,name=step,proto3,oneof" json:"step,omitempty"`
	// If true, the sequence will wrap around to the minimum value once the maximum
	// is reached (or vice versa for descending sequences).
	Cycle         bool `protobuf:"varint,4,opt,name=cycle,proto3" json:"cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoIncrement) Reset() {
	*x = AutoIncrement{}
	mi := &file_core_shared_auto_increment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoIncrement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoIncrement) ProtoMessage() {}

func (x *AutoIncrement) ProtoReflect() protoreflect.Message {
	mi := &file_core_shared_auto_increment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoIncrement.ProtoReflect.Descriptor instead.
func (*AutoIncrement) Descriptor() ([]byte, []int) {
	return file_core_shared_auto_increment_proto_rawDescGZIP(), []int{0}
}

func (x *AutoIncrement) GetMin() int64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *AutoIncrement) GetMax() int64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *AutoIncrement) GetStep() int64 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *AutoIncrement) GetCycle() bool {
	if x != nil {
		return x.Cycle
	}
	return false
}

var File_core_shared_auto_increment_proto protoreflect.FileDescriptor

const file_core_shared_auto_increment_proto_rawDesc = "" +
	"\n" +
	" core/shared/auto_increment.proto\x12\vcore.shared\"\x85\x01\n" +
	"\rAutoIncrement\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x03H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x03H\x01R\x03max\x88\x01\x01\x12\x17\n" +
	"\x04step\x18\x03 \x01(\x03H\x02R\x04step\x88\x01\x01\x12\x14\n" +
	"\x05cycle\x18\x04 \x01(\bR\x05cycleB\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_maxB\a\n" +
	"\x05_stepB\xa3\x01\n" +
	"\x0fcom.core.sharedB\x12AutoIncrementProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_auto_increment_proto_rawDescOnce sync.Once
	file_core_shared_auto_increment_proto_rawDescData []byte
)

func file_core_shared_auto_increment_proto_rawDescGZIP() []byte {
	file_core_shared_auto_increment_proto_rawDescOnce.Do(func() {
		file_core_shared_auto_increment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_auto_increment_proto_rawDesc), len(file_core_shared_auto_increment_proto_rawDesc)))
	})
	return file_core_shared_auto_increment_proto_rawDescData
}

var file_core_shared_auto_increment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_shared_auto_increment_proto_goTypes = []any{
	(*AutoIncrement)(nil), // 0: core.shared.AutoIncrement
}
var file_core_shared_auto_increment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_shared_auto_increment_proto_init() }
func file_core_shared_auto_increment_proto_init() {
	if File_core_shared_auto_increment_proto != nil {
		return
	}
	file_core_shared_auto_increment_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_auto_increment_proto_rawDesc), len(file_core_shared_auto_increment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_auto_increment_proto_goTypes,
		DependencyIndexes: file_core_shared_auto_increment_proto_depIdxs,
		MessageInfos:      file_core_shared_auto_increment_proto_msgTypes,
	}.Build()
	File_core_shared_auto_increment_proto = out.File
	file_core_shared_auto_increment_proto_goTypes = nil
	file_core_shared_auto_increment_proto_depIdxs = nil
}
