// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/shared/deferrable_state.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeferrableState specifies whether a constraint's validity is checked immediately
// after every statement, or if it can be deferred until the end of the transaction.
type DeferrableState int32

const (
	// Unspecified deferrable state.
	DeferrableState_DEFERRABLE_STATE_UNSPECIFIED DeferrableState = 0
	// The constraint is checked immediately after each statement. It cannot be deferred.
	// This is the strict default behavior in almost all SQL databases.
	DeferrableState_DEFERRABLE_STATE_NOT_DEFERRABLE DeferrableState = 1
	// The constraint is checked immediately by default, but can be explicitly deferred
	// for a specific transaction using `SET CONSTRAINTS ALL DEFERRED`.
	DeferrableState_DEFERRABLE_STATE_INITIALLY_IMMEDIATE DeferrableState = 2
	// The constraint check is automatically postponed until the `COMMIT`
	// of the transaction.
	DeferrableState_DEFERRABLE_STATE_INITIALLY_DEFERRED DeferrableState = 3
)

// Enum value maps for DeferrableState.
var (
	DeferrableState_name = map[int32]string{
		0: "DEFERRABLE_STATE_UNSPECIFIED",
		1: "DEFERRABLE_STATE_NOT_DEFERRABLE",
		2: "DEFERRABLE_STATE_INITIALLY_IMMEDIATE",
		3: "DEFERRABLE_STATE_INITIALLY_DEFERRED",
	}
	DeferrableState_value = map[string]int32{
		"DEFERRABLE_STATE_UNSPECIFIED":         0,
		"DEFERRABLE_STATE_NOT_DEFERRABLE":      1,
		"DEFERRABLE_STATE_INITIALLY_IMMEDIATE": 2,
		"DEFERRABLE_STATE_INITIALLY_DEFERRED":  3,
	}
)

func (x DeferrableState) Enum() *DeferrableState {
	p := new(DeferrableState)
	*p = x
	return p
}

func (x DeferrableState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeferrableState) Descriptor() protoreflect.EnumDescriptor {
	return file_core_shared_deferrable_state_proto_enumTypes[0].Descriptor()
}

func (DeferrableState) Type() protoreflect.EnumType {
	return &file_core_shared_deferrable_state_proto_enumTypes[0]
}

func (x DeferrableState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeferrableState.Descriptor instead.
func (DeferrableState) EnumDescriptor() ([]byte, []int) {
	return file_core_shared_deferrable_state_proto_rawDescGZIP(), []int{0}
}

var File_core_shared_deferrable_state_proto protoreflect.FileDescriptor

const file_core_shared_deferrable_state_proto_rawDesc = "" +
	"\n" +
	"\"core/shared/deferrable_state.proto\x12\vcore.shared*\xab\x01\n" +
	"\x0fDeferrableState\x12 \n" +
	"\x1cDEFERRABLE_STATE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fDEFERRABLE_STATE_NOT_DEFERRABLE\x10\x01\x12(\n" +
	"$DEFERRABLE_STATE_INITIALLY_IMMEDIATE\x10\x02\x12'\n" +
	"#DEFERRABLE_STATE_INITIALLY_DEFERRED\x10\x03B\xa5\x01\n" +
	"\x0fcom.core.sharedB\x14DeferrableStateProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_deferrable_state_proto_rawDescOnce sync.Once
	file_core_shared_deferrable_state_proto_rawDescData []byte
)

func file_core_shared_deferrable_state_proto_rawDescGZIP() []byte {
	file_core_shared_deferrable_state_proto_rawDescOnce.Do(func() {
		file_core_shared_deferrable_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_deferrable_state_proto_rawDesc), len(file_core_shared_deferrable_state_proto_rawDesc)))
	})
	return file_core_shared_deferrable_state_proto_rawDescData
}

var file_core_shared_deferrable_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_shared_deferrable_state_proto_goTypes = []any{
	(DeferrableState)(0), // 0: core.shared.DeferrableState
}
var file_core_shared_deferrable_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_shared_deferrable_state_proto_init() }
func file_core_shared_deferrable_state_proto_init() {
	if File_core_shared_deferrable_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_deferrable_state_proto_rawDesc), len(file_core_shared_deferrable_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_deferrable_state_proto_goTypes,
		DependencyIndexes: file_core_shared_deferrable_state_proto_depIdxs,
		EnumInfos:         file_core_shared_deferrable_state_proto_enumTypes,
	}.Build()
	File_core_shared_deferrable_state_proto = out.File
	file_core_shared_deferrable_state_proto_goTypes = nil
	file_core_shared_deferrable_state_proto_depIdxs = nil
}
