// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/shared/foreign_key_action.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForeignKeyAction specifies the referential database action triggered
// when a referenced row is updated or deleted.
type ForeignKeyAction int32

const (
	// Unspecified referential action.
	ForeignKeyAction_FOREIGN_KEY_ACTION_UNSPECIFIED ForeignKeyAction = 0
	// Produces an error indicating that the deletion or update would create a
	// foreign key constraint violation. If the constraint is deferred, this
	// error will be produced at constraint check time if there still exist
	// any referencing rows.
	ForeignKeyAction_FOREIGN_KEY_ACTION_NO_ACTION ForeignKeyAction = 1
	// Produces an error indicating that the deletion or update would create a
	// foreign key constraint violation. This is the same as NO ACTION except
	// that the check is not deferrable.
	ForeignKeyAction_FOREIGN_KEY_ACTION_RESTRICT ForeignKeyAction = 2
	// Delete any rows referencing the deleted row, or update the values of the
	// referencing column(s) to the new values of the referenced columns.
	ForeignKeyAction_FOREIGN_KEY_ACTION_CASCADE ForeignKeyAction = 3
	// Set the referencing column(s) to null.
	ForeignKeyAction_FOREIGN_KEY_ACTION_SET_NULL ForeignKeyAction = 4
	// Set the referencing column(s) to their default values.
	ForeignKeyAction_FOREIGN_KEY_ACTION_SET_DEFAULT ForeignKeyAction = 5
)

// Enum value maps for ForeignKeyAction.
var (
	ForeignKeyAction_name = map[int32]string{
		0: "FOREIGN_KEY_ACTION_UNSPECIFIED",
		1: "FOREIGN_KEY_ACTION_NO_ACTION",
		2: "FOREIGN_KEY_ACTION_RESTRICT",
		3: "FOREIGN_KEY_ACTION_CASCADE",
		4: "FOREIGN_KEY_ACTION_SET_NULL",
		5: "FOREIGN_KEY_ACTION_SET_DEFAULT",
	}
	ForeignKeyAction_value = map[string]int32{
		"FOREIGN_KEY_ACTION_UNSPECIFIED": 0,
		"FOREIGN_KEY_ACTION_NO_ACTION":   1,
		"FOREIGN_KEY_ACTION_RESTRICT":    2,
		"FOREIGN_KEY_ACTION_CASCADE":     3,
		"FOREIGN_KEY_ACTION_SET_NULL":    4,
		"FOREIGN_KEY_ACTION_SET_DEFAULT": 5,
	}
)

func (x ForeignKeyAction) Enum() *ForeignKeyAction {
	p := new(ForeignKeyAction)
	*p = x
	return p
}

func (x ForeignKeyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForeignKeyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_core_shared_foreign_key_action_proto_enumTypes[0].Descriptor()
}

func (ForeignKeyAction) Type() protoreflect.EnumType {
	return &file_core_shared_foreign_key_action_proto_enumTypes[0]
}

func (x ForeignKeyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForeignKeyAction.Descriptor instead.
func (ForeignKeyAction) EnumDescriptor() ([]byte, []int) {
	return file_core_shared_foreign_key_action_proto_rawDescGZIP(), []int{0}
}

var File_core_shared_foreign_key_action_proto protoreflect.FileDescriptor

const file_core_shared_foreign_key_action_proto_rawDesc = "" +
	"\n" +
	"$core/shared/foreign_key_action.proto\x12\vcore.shared*\xde\x01\n" +
	"\x10ForeignKeyAction\x12\"\n" +
	"\x1eFOREIGN_KEY_ACTION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cFOREIGN_KEY_ACTION_NO_ACTION\x10\x01\x12\x1f\n" +
	"\x1bFOREIGN_KEY_ACTION_RESTRICT\x10\x02\x12\x1e\n" +
	"\x1aFOREIGN_KEY_ACTION_CASCADE\x10\x03\x12\x1f\n" +
	"\x1bFOREIGN_KEY_ACTION_SET_NULL\x10\x04\x12\"\n" +
	"\x1eFOREIGN_KEY_ACTION_SET_DEFAULT\x10\x05B\xa6\x01\n" +
	"\x0fcom.core.sharedB\x15ForeignKeyActionProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_foreign_key_action_proto_rawDescOnce sync.Once
	file_core_shared_foreign_key_action_proto_rawDescData []byte
)

func file_core_shared_foreign_key_action_proto_rawDescGZIP() []byte {
	file_core_shared_foreign_key_action_proto_rawDescOnce.Do(func() {
		file_core_shared_foreign_key_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_foreign_key_action_proto_rawDesc), len(file_core_shared_foreign_key_action_proto_rawDesc)))
	})
	return file_core_shared_foreign_key_action_proto_rawDescData
}

var file_core_shared_foreign_key_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_shared_foreign_key_action_proto_goTypes = []any{
	(ForeignKeyAction)(0), // 0: core.shared.ForeignKeyAction
}
var file_core_shared_foreign_key_action_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_shared_foreign_key_action_proto_init() }
func file_core_shared_foreign_key_action_proto_init() {
	if File_core_shared_foreign_key_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_foreign_key_action_proto_rawDesc), len(file_core_shared_foreign_key_action_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_foreign_key_action_proto_goTypes,
		DependencyIndexes: file_core_shared_foreign_key_action_proto_depIdxs,
		EnumInfos:         file_core_shared_foreign_key_action_proto_enumTypes,
	}.Build()
	File_core_shared_foreign_key_action_proto = out.File
	file_core_shared_foreign_key_action_proto_goTypes = nil
	file_core_shared_foreign_key_action_proto_depIdxs = nil
}
