// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/shared/foreign_key.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForeignKey represents a strictly enforced referential database constraint
// linking columns in a local table to columns in a target table.
type ForeignKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique identifier for the foreign key constraint.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The fully qualified target table this foreign key points to
	// (e.g. 'public.users' or 'users').
	TargetTable string `protobuf:"bytes,2,opt,name=target_table,json=targetTable,proto3" json:"target_table,omitempty"`
	// Mappings of local source columns to the referenced target columns.
	// Multiple mappings indicate a composite foreign key constraint.
	Columns []*ForeignKeyColumnMapping `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	// The referential action triggered when the referenced row is deleted.
	OnDelete ForeignKeyAction `protobuf:"varint,4,opt,name=on_delete,json=onDelete,proto3,enum=core.shared.ForeignKeyAction" json:"on_delete,omitempty"`
	// The referential action triggered when the referenced row is updated.
	OnUpdate ForeignKeyAction `protobuf:"varint,5,opt,name=on_update,json=onUpdate,proto3,enum=core.shared.ForeignKeyAction" json:"on_update,omitempty"`
	// Controls when the foreign key constraint is validated during a transaction.
	Deferrable    DeferrableState `protobuf:"varint,6,opt,name=deferrable,proto3,enum=core.shared.DeferrableState" json:"deferrable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForeignKey) Reset() {
	*x = ForeignKey{}
	mi := &file_core_shared_foreign_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForeignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignKey) ProtoMessage() {}

func (x *ForeignKey) ProtoReflect() protoreflect.Message {
	mi := &file_core_shared_foreign_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignKey.ProtoReflect.Descriptor instead.
func (*ForeignKey) Descriptor() ([]byte, []int) {
	return file_core_shared_foreign_key_proto_rawDescGZIP(), []int{0}
}

func (x *ForeignKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForeignKey) GetTargetTable() string {
	if x != nil {
		return x.TargetTable
	}
	return ""
}

func (x *ForeignKey) GetColumns() []*ForeignKeyColumnMapping {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ForeignKey) GetOnDelete() ForeignKeyAction {
	if x != nil {
		return x.OnDelete
	}
	return ForeignKeyAction_FOREIGN_KEY_ACTION_UNSPECIFIED
}

func (x *ForeignKey) GetOnUpdate() ForeignKeyAction {
	if x != nil {
		return x.OnUpdate
	}
	return ForeignKeyAction_FOREIGN_KEY_ACTION_UNSPECIFIED
}

func (x *ForeignKey) GetDeferrable() DeferrableState {
	if x != nil {
		return x.Deferrable
	}
	return DeferrableState_DEFERRABLE_STATE_UNSPECIFIED
}

var File_core_shared_foreign_key_proto protoreflect.FileDescriptor

const file_core_shared_foreign_key_proto_rawDesc = "" +
	"\n" +
	"\x1dcore/shared/foreign_key.proto\x12\vcore.shared\x1a$core/shared/foreign_key_action.proto\x1a\"core/shared/deferrable_state.proto\x1a,core/shared/foreign_key_column_mapping.proto\"\xb9\x02\n" +
	"\n" +
	"ForeignKey\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ftarget_table\x18\x02 \x01(\tR\vtargetTable\x12>\n" +
	"\acolumns\x18\x03 \x03(\v2$.core.shared.ForeignKeyColumnMappingR\acolumns\x12:\n" +
	"\ton_delete\x18\x04 \x01(\x0e2\x1d.core.shared.ForeignKeyActionR\bonDelete\x12:\n" +
	"\ton_update\x18\x05 \x01(\x0e2\x1d.core.shared.ForeignKeyActionR\bonUpdate\x12<\n" +
	"\n" +
	"deferrable\x18\x06 \x01(\x0e2\x1c.core.shared.DeferrableStateR\n" +
	"deferrableB\xa0\x01\n" +
	"\x0fcom.core.sharedB\x0fForeignKeyProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_foreign_key_proto_rawDescOnce sync.Once
	file_core_shared_foreign_key_proto_rawDescData []byte
)

func file_core_shared_foreign_key_proto_rawDescGZIP() []byte {
	file_core_shared_foreign_key_proto_rawDescOnce.Do(func() {
		file_core_shared_foreign_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_foreign_key_proto_rawDesc), len(file_core_shared_foreign_key_proto_rawDesc)))
	})
	return file_core_shared_foreign_key_proto_rawDescData
}

var file_core_shared_foreign_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_shared_foreign_key_proto_goTypes = []any{
	(*ForeignKey)(nil),              // 0: core.shared.ForeignKey
	(*ForeignKeyColumnMapping)(nil), // 1: core.shared.ForeignKeyColumnMapping
	(ForeignKeyAction)(0),           // 2: core.shared.ForeignKeyAction
	(DeferrableState)(0),            // 3: core.shared.DeferrableState
}
var file_core_shared_foreign_key_proto_depIdxs = []int32{
	1, // 0: core.shared.ForeignKey.columns:type_name -> core.shared.ForeignKeyColumnMapping
	2, // 1: core.shared.ForeignKey.on_delete:type_name -> core.shared.ForeignKeyAction
	2, // 2: core.shared.ForeignKey.on_update:type_name -> core.shared.ForeignKeyAction
	3, // 3: core.shared.ForeignKey.deferrable:type_name -> core.shared.DeferrableState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_shared_foreign_key_proto_init() }
func file_core_shared_foreign_key_proto_init() {
	if File_core_shared_foreign_key_proto != nil {
		return
	}
	file_core_shared_foreign_key_action_proto_init()
	file_core_shared_deferrable_state_proto_init()
	file_core_shared_foreign_key_column_mapping_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_foreign_key_proto_rawDesc), len(file_core_shared_foreign_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_foreign_key_proto_goTypes,
		DependencyIndexes: file_core_shared_foreign_key_proto_depIdxs,
		MessageInfos:      file_core_shared_foreign_key_proto_msgTypes,
	}.Build()
	File_core_shared_foreign_key_proto = out.File
	file_core_shared_foreign_key_proto_goTypes = nil
	file_core_shared_foreign_key_proto_depIdxs = nil
}
