// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/shared/relation.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Relation specifies an explicit non-constraint link to another table.
// It is primarily used to instruct the code generator on how to eagerly
// load related structures in the ORM.
type Relation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique name for the relation, used in the generated code
	// (e.g. 'posts', 'author').
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The type/cardinality of the relationship (e.g. 1:N, N:1).
	Type RelationType `protobuf:"varint,2,opt,name=type,proto3,enum=core.shared.RelationType" json:"type,omitempty"`
	// The fully qualified target table this relation points to
	// (e.g. 'public.users' or 'users').
	TargetTable string `protobuf:"bytes,3,opt,name=target_table,json=targetTable,proto3" json:"target_table,omitempty"`
	// The columns connecting the source table to the target table.
	Columns       []*RelationColumnMapping `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_core_shared_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_core_shared_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_core_shared_relation_proto_rawDescGZIP(), []int{0}
}

func (x *Relation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Relation) GetType() RelationType {
	if x != nil {
		return x.Type
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (x *Relation) GetTargetTable() string {
	if x != nil {
		return x.TargetTable
	}
	return ""
}

func (x *Relation) GetColumns() []*RelationColumnMapping {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_core_shared_relation_proto protoreflect.FileDescriptor

const file_core_shared_relation_proto_rawDesc = "" +
	"\n" +
	"\x1acore/shared/relation.proto\x12\vcore.shared\x1a\x1fcore/shared/relation_type.proto\x1a)core/shared/relation_column_mapping.proto\"\xae\x01\n" +
	"\bRelation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.core.shared.RelationTypeR\x04type\x12!\n" +
	"\ftarget_table\x18\x03 \x01(\tR\vtargetTable\x12<\n" +
	"\acolumns\x18\x04 \x03(\v2\".core.shared.RelationColumnMappingR\acolumnsB\x9e\x01\n" +
	"\x0fcom.core.sharedB\rRelationProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_relation_proto_rawDescOnce sync.Once
	file_core_shared_relation_proto_rawDescData []byte
)

func file_core_shared_relation_proto_rawDescGZIP() []byte {
	file_core_shared_relation_proto_rawDescOnce.Do(func() {
		file_core_shared_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_relation_proto_rawDesc), len(file_core_shared_relation_proto_rawDesc)))
	})
	return file_core_shared_relation_proto_rawDescData
}

var file_core_shared_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_shared_relation_proto_goTypes = []any{
	(*Relation)(nil),              // 0: core.shared.Relation
	(RelationType)(0),             // 1: core.shared.RelationType
	(*RelationColumnMapping)(nil), // 2: core.shared.RelationColumnMapping
}
var file_core_shared_relation_proto_depIdxs = []int32{
	1, // 0: core.shared.Relation.type:type_name -> core.shared.RelationType
	2, // 1: core.shared.Relation.columns:type_name -> core.shared.RelationColumnMapping
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_shared_relation_proto_init() }
func file_core_shared_relation_proto_init() {
	if File_core_shared_relation_proto != nil {
		return
	}
	file_core_shared_relation_type_proto_init()
	file_core_shared_relation_column_mapping_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_relation_proto_rawDesc), len(file_core_shared_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_relation_proto_goTypes,
		DependencyIndexes: file_core_shared_relation_proto_depIdxs,
		MessageInfos:      file_core_shared_relation_proto_msgTypes,
	}.Build()
	File_core_shared_relation_proto = out.File
	file_core_shared_relation_proto_goTypes = nil
	file_core_shared_relation_proto_depIdxs = nil
}
