// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/shared/relation_type.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelationType defines the multiplicity of a relationship between two tables.
type RelationType int32

const (
	// Unspecified or unknown relationship type.
	RelationType_RELATION_TYPE_UNSPECIFIED RelationType = 0
	// Represents a 1:1 relationship where each row in the source table
	// corresponds to at most one row in the target table.
	RelationType_RELATION_TYPE_ONE_TO_ONE RelationType = 1
	// Represents a 1:N relationship where a single row in the source table
	// can relate to multiple rows in the target table.
	RelationType_RELATION_TYPE_ONE_TO_MANY RelationType = 2
	// Represents an N:1 relationship where multiple rows in the source table
	// can relate to a single row in the target table (typically a foreign key).
	RelationType_RELATION_TYPE_MANY_TO_ONE RelationType = 3
	// Represents an N:M relationship where multiple rows in the source table
	// can relate to multiple rows in the target table (typically via a join table).
	RelationType_RELATION_TYPE_MANY_TO_MANY RelationType = 4
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "RELATION_TYPE_UNSPECIFIED",
		1: "RELATION_TYPE_ONE_TO_ONE",
		2: "RELATION_TYPE_ONE_TO_MANY",
		3: "RELATION_TYPE_MANY_TO_ONE",
		4: "RELATION_TYPE_MANY_TO_MANY",
	}
	RelationType_value = map[string]int32{
		"RELATION_TYPE_UNSPECIFIED":  0,
		"RELATION_TYPE_ONE_TO_ONE":   1,
		"RELATION_TYPE_ONE_TO_MANY":  2,
		"RELATION_TYPE_MANY_TO_ONE":  3,
		"RELATION_TYPE_MANY_TO_MANY": 4,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_shared_relation_type_proto_enumTypes[0].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_core_shared_relation_type_proto_enumTypes[0]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_core_shared_relation_type_proto_rawDescGZIP(), []int{0}
}

var File_core_shared_relation_type_proto protoreflect.FileDescriptor

const file_core_shared_relation_type_proto_rawDesc = "" +
	"\n" +
	"\x1fcore/shared/relation_type.proto\x12\vcore.shared*\xa9\x01\n" +
	"\fRelationType\x12\x1d\n" +
	"\x19RELATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RELATION_TYPE_ONE_TO_ONE\x10\x01\x12\x1d\n" +
	"\x19RELATION_TYPE_ONE_TO_MANY\x10\x02\x12\x1d\n" +
	"\x19RELATION_TYPE_MANY_TO_ONE\x10\x03\x12\x1e\n" +
	"\x1aRELATION_TYPE_MANY_TO_MANY\x10\x04B\xa2\x01\n" +
	"\x0fcom.core.sharedB\x11RelationTypeProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_relation_type_proto_rawDescOnce sync.Once
	file_core_shared_relation_type_proto_rawDescData []byte
)

func file_core_shared_relation_type_proto_rawDescGZIP() []byte {
	file_core_shared_relation_type_proto_rawDescOnce.Do(func() {
		file_core_shared_relation_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_relation_type_proto_rawDesc), len(file_core_shared_relation_type_proto_rawDesc)))
	})
	return file_core_shared_relation_type_proto_rawDescData
}

var file_core_shared_relation_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_shared_relation_type_proto_goTypes = []any{
	(RelationType)(0), // 0: core.shared.RelationType
}
var file_core_shared_relation_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_shared_relation_type_proto_init() }
func file_core_shared_relation_type_proto_init() {
	if File_core_shared_relation_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_relation_type_proto_rawDesc), len(file_core_shared_relation_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_relation_type_proto_goTypes,
		DependencyIndexes: file_core_shared_relation_type_proto_depIdxs,
		EnumInfos:         file_core_shared_relation_type_proto_enumTypes,
	}.Build()
	File_core_shared_relation_type_proto = out.File
	file_core_shared_relation_type_proto_goTypes = nil
	file_core_shared_relation_type_proto_depIdxs = nil
}
