// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/shared/sort_order.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortOrder specifies the ascending or descending sorting direction
// applied to an index column.
type SortOrder int32

const (
	// Unspecified sort order (usually defaults to ASC depending on engine).
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	// Sorts the values in ascending order (smallest to largest).
	SortOrder_SORT_ORDER_ASC SortOrder = 1
	// Sorts the values in descending order (largest to smallest).
	SortOrder_SORT_ORDER_DESC SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_core_shared_sort_order_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_core_shared_sort_order_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_core_shared_sort_order_proto_rawDescGZIP(), []int{0}
}

var File_core_shared_sort_order_proto protoreflect.FileDescriptor

const file_core_shared_sort_order_proto_rawDesc = "" +
	"\n" +
	"\x1ccore/shared/sort_order.proto\x12\vcore.shared*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02B\x9f\x01\n" +
	"\x0fcom.core.sharedB\x0eSortOrderProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_sort_order_proto_rawDescOnce sync.Once
	file_core_shared_sort_order_proto_rawDescData []byte
)

func file_core_shared_sort_order_proto_rawDescGZIP() []byte {
	file_core_shared_sort_order_proto_rawDescOnce.Do(func() {
		file_core_shared_sort_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_sort_order_proto_rawDesc), len(file_core_shared_sort_order_proto_rawDesc)))
	})
	return file_core_shared_sort_order_proto_rawDescData
}

var file_core_shared_sort_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_shared_sort_order_proto_goTypes = []any{
	(SortOrder)(0), // 0: core.shared.SortOrder
}
var file_core_shared_sort_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_shared_sort_order_proto_init() }
func file_core_shared_sort_order_proto_init() {
	if File_core_shared_sort_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_sort_order_proto_rawDesc), len(file_core_shared_sort_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_sort_order_proto_goTypes,
		DependencyIndexes: file_core_shared_sort_order_proto_depIdxs,
		EnumInfos:         file_core_shared_sort_order_proto_enumTypes,
	}.Build()
	File_core_shared_sort_order_proto = out.File
	file_core_shared_sort_order_proto_goTypes = nil
	file_core_shared_sort_order_proto_depIdxs = nil
}
