// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/shared/table_reference.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TableReference represents a fully qualified reference to a database table.
// It includes the database name, schema name, and table name components
// that together uniquely identify a table.
type TableReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the logical database containing the table.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Name of the logical schema (or namespace) within the database.
	Schema string `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// Name of the table within the schema.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableReference) Reset() {
	*x = TableReference{}
	mi := &file_core_shared_table_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableReference) ProtoMessage() {}

func (x *TableReference) ProtoReflect() protoreflect.Message {
	mi := &file_core_shared_table_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableReference.ProtoReflect.Descriptor instead.
func (*TableReference) Descriptor() ([]byte, []int) {
	return file_core_shared_table_reference_proto_rawDescGZIP(), []int{0}
}

func (x *TableReference) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *TableReference) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *TableReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_core_shared_table_reference_proto protoreflect.FileDescriptor

const file_core_shared_table_reference_proto_rawDesc = "" +
	"\n" +
	"!core/shared/table_reference.proto\x12\vcore.shared\"X\n" +
	"\x0eTableReference\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameB\xa4\x01\n" +
	"\x0fcom.core.sharedB\x13TableReferenceProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_table_reference_proto_rawDescOnce sync.Once
	file_core_shared_table_reference_proto_rawDescData []byte
)

func file_core_shared_table_reference_proto_rawDescGZIP() []byte {
	file_core_shared_table_reference_proto_rawDescOnce.Do(func() {
		file_core_shared_table_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_table_reference_proto_rawDesc), len(file_core_shared_table_reference_proto_rawDesc)))
	})
	return file_core_shared_table_reference_proto_rawDescData
}

var file_core_shared_table_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_shared_table_reference_proto_goTypes = []any{
	(*TableReference)(nil), // 0: core.shared.TableReference
}
var file_core_shared_table_reference_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_shared_table_reference_proto_init() }
func file_core_shared_table_reference_proto_init() {
	if File_core_shared_table_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_table_reference_proto_rawDesc), len(file_core_shared_table_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_table_reference_proto_goTypes,
		DependencyIndexes: file_core_shared_table_reference_proto_depIdxs,
		MessageInfos:      file_core_shared_table_reference_proto_msgTypes,
	}.Build()
	File_core_shared_table_reference_proto = out.File
	file_core_shared_table_reference_proto_goTypes = nil
	file_core_shared_table_reference_proto_depIdxs = nil
}
