// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: core/shared/virtual_foreign_key.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VirtualForeignKey represents a relationship between tables that functions
// exactly like a standard foreign key for ORMs, query builders, and code
// generation, but does NOT result in an actual database constraint being
// physically created or enforced by the database engine.
type VirtualForeignKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique identifier for the virtual foreign key, used for codegen relations.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The fully qualified target table this virtual key points to
	// (e.g. 'public.users' or 'users').
	TargetTable string `protobuf:"bytes,2,opt,name=target_table,json=targetTable,proto3" json:"target_table,omitempty"`
	// Mappings of local source columns to the referenced target columns.
	Columns       []*ForeignKeyColumnMapping `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualForeignKey) Reset() {
	*x = VirtualForeignKey{}
	mi := &file_core_shared_virtual_foreign_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualForeignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualForeignKey) ProtoMessage() {}

func (x *VirtualForeignKey) ProtoReflect() protoreflect.Message {
	mi := &file_core_shared_virtual_foreign_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualForeignKey.ProtoReflect.Descriptor instead.
func (*VirtualForeignKey) Descriptor() ([]byte, []int) {
	return file_core_shared_virtual_foreign_key_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualForeignKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualForeignKey) GetTargetTable() string {
	if x != nil {
		return x.TargetTable
	}
	return ""
}

func (x *VirtualForeignKey) GetColumns() []*ForeignKeyColumnMapping {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_core_shared_virtual_foreign_key_proto protoreflect.FileDescriptor

const file_core_shared_virtual_foreign_key_proto_rawDesc = "" +
	"\n" +
	"%core/shared/virtual_foreign_key.proto\x12\vcore.shared\x1a,core/shared/foreign_key_column_mapping.proto\"\x8a\x01\n" +
	"\x11VirtualForeignKey\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ftarget_table\x18\x02 \x01(\tR\vtargetTable\x12>\n" +
	"\acolumns\x18\x03 \x03(\v2$.core.shared.ForeignKeyColumnMappingR\acolumnsB\xa7\x01\n" +
	"\x0fcom.core.sharedB\x16VirtualForeignKeyProtoP\x01Z/github.com/uthereal/scheme/genproto/core/shared\xa2\x02\x03CSX\xaa\x02\vCore.Shared\xca\x02\vCore\\Shared\xe2\x02\x17Core\\Shared\\GPBMetadata\xea\x02\fCore::Sharedb\x06proto3"

var (
	file_core_shared_virtual_foreign_key_proto_rawDescOnce sync.Once
	file_core_shared_virtual_foreign_key_proto_rawDescData []byte
)

func file_core_shared_virtual_foreign_key_proto_rawDescGZIP() []byte {
	file_core_shared_virtual_foreign_key_proto_rawDescOnce.Do(func() {
		file_core_shared_virtual_foreign_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_shared_virtual_foreign_key_proto_rawDesc), len(file_core_shared_virtual_foreign_key_proto_rawDesc)))
	})
	return file_core_shared_virtual_foreign_key_proto_rawDescData
}

var file_core_shared_virtual_foreign_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_shared_virtual_foreign_key_proto_goTypes = []any{
	(*VirtualForeignKey)(nil),       // 0: core.shared.VirtualForeignKey
	(*ForeignKeyColumnMapping)(nil), // 1: core.shared.ForeignKeyColumnMapping
}
var file_core_shared_virtual_foreign_key_proto_depIdxs = []int32{
	1, // 0: core.shared.VirtualForeignKey.columns:type_name -> core.shared.ForeignKeyColumnMapping
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_shared_virtual_foreign_key_proto_init() }
func file_core_shared_virtual_foreign_key_proto_init() {
	if File_core_shared_virtual_foreign_key_proto != nil {
		return
	}
	file_core_shared_foreign_key_column_mapping_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_shared_virtual_foreign_key_proto_rawDesc), len(file_core_shared_virtual_foreign_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_shared_virtual_foreign_key_proto_goTypes,
		DependencyIndexes: file_core_shared_virtual_foreign_key_proto_depIdxs,
		MessageInfos:      file_core_shared_virtual_foreign_key_proto_msgTypes,
	}.Build()
	File_core_shared_virtual_foreign_key_proto = out.File
	file_core_shared_virtual_foreign_key_proto_goTypes = nil
	file_core_shared_virtual_foreign_key_proto_depIdxs = nil
}
