// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/check_constraint.proto

package postgres

import (
	shared "github.com/uthereal/scheme/genproto/core/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckConstraint represents a database check constraint, ensuring that values
// satisfy a specific boolean expression before they can be inserted or updated.
type CheckConstraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique identifier for the check constraint.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The primary column this check constraint applies to.
	// (Note: The predicate itself may reference multiple columns for table-level checks).
	Column string `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	// The boolean SQL expression that must evaluate to true or unknown (e.g., 'price > 0').
	Predicate string `protobuf:"bytes,3,opt,name=predicate,proto3" json:"predicate,omitempty"`
	// Controls when the check constraint is validated during a transaction.
	Deferrable shared.DeferrableState `protobuf:"varint,4,opt,name=deferrable,proto3,enum=core.shared.DeferrableState" json:"deferrable,omitempty"`
	// If true, the constraint is not automatically inherited by child tables or partitions
	// (PostgreSQL-specific 'NO INHERIT' clause).
	NoInherit bool `protobuf:"varint,5,opt,name=no_inherit,json=noInherit,proto3" json:"no_inherit,omitempty"`
	// The previous name of this object, used to issue RENAME commands instead of DROP/CREATE.
	NamePrevious  string `protobuf:"bytes,6,opt,name=name_previous,json=namePrevious,proto3" json:"name_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConstraint) Reset() {
	*x = CheckConstraint{}
	mi := &file_postgres_check_constraint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConstraint) ProtoMessage() {}

func (x *CheckConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_check_constraint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConstraint.ProtoReflect.Descriptor instead.
func (*CheckConstraint) Descriptor() ([]byte, []int) {
	return file_postgres_check_constraint_proto_rawDescGZIP(), []int{0}
}

func (x *CheckConstraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckConstraint) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *CheckConstraint) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *CheckConstraint) GetDeferrable() shared.DeferrableState {
	if x != nil {
		return x.Deferrable
	}
	return shared.DeferrableState(0)
}

func (x *CheckConstraint) GetNoInherit() bool {
	if x != nil {
		return x.NoInherit
	}
	return false
}

func (x *CheckConstraint) GetNamePrevious() string {
	if x != nil {
		return x.NamePrevious
	}
	return ""
}

var File_postgres_check_constraint_proto protoreflect.FileDescriptor

const file_postgres_check_constraint_proto_rawDesc = "" +
	"\n" +
	"\x1fpostgres/check_constraint.proto\x12\bpostgres\x1a\"core/shared/deferrable_state.proto\"\xdd\x01\n" +
	"\x0fCheckConstraint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\x12\x1c\n" +
	"\tpredicate\x18\x03 \x01(\tR\tpredicate\x12<\n" +
	"\n" +
	"deferrable\x18\x04 \x01(\x0e2\x1c.core.shared.DeferrableStateR\n" +
	"deferrable\x12\x1d\n" +
	"\n" +
	"no_inherit\x18\x05 \x01(\bR\tnoInherit\x12#\n" +
	"\rname_previous\x18\x06 \x01(\tR\fnamePreviousB\x92\x01\n" +
	"\fcom.postgresB\x14CheckConstraintProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_check_constraint_proto_rawDescOnce sync.Once
	file_postgres_check_constraint_proto_rawDescData []byte
)

func file_postgres_check_constraint_proto_rawDescGZIP() []byte {
	file_postgres_check_constraint_proto_rawDescOnce.Do(func() {
		file_postgres_check_constraint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_check_constraint_proto_rawDesc), len(file_postgres_check_constraint_proto_rawDesc)))
	})
	return file_postgres_check_constraint_proto_rawDescData
}

var file_postgres_check_constraint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_check_constraint_proto_goTypes = []any{
	(*CheckConstraint)(nil),     // 0: postgres.CheckConstraint
	(shared.DeferrableState)(0), // 1: core.shared.DeferrableState
}
var file_postgres_check_constraint_proto_depIdxs = []int32{
	1, // 0: postgres.CheckConstraint.deferrable:type_name -> core.shared.DeferrableState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgres_check_constraint_proto_init() }
func file_postgres_check_constraint_proto_init() {
	if File_postgres_check_constraint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_check_constraint_proto_rawDesc), len(file_postgres_check_constraint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_check_constraint_proto_goTypes,
		DependencyIndexes: file_postgres_check_constraint_proto_depIdxs,
		MessageInfos:      file_postgres_check_constraint_proto_msgTypes,
	}.Build()
	File_postgres_check_constraint_proto = out.File
	file_postgres_check_constraint_proto_goTypes = nil
	file_postgres_check_constraint_proto_depIdxs = nil
}
