// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/column.proto

package postgres

import (
	shared "github.com/uthereal/scheme/genproto/core/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Column represents a single structural column within a PostgreSQL database table.
type Column struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The physical name of the column as it appears in the database.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The specific PostgreSQL data type of the column, including optional parameters
	// like precision, scale, or length.
	Type *DataType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Indicates whether the column is allowed to store NULL values.
	IsNullable bool `protobuf:"varint,3,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	// The default value expression applied if no value is provided during insertion
	// (e.g., 'now()', '0', '"untitled"').
	DefaultValue string `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// Auto-increment sequence configuration (e.g., GENERATED AS IDENTITY).
	AutoIncrement *shared.AutoIncrement `protobuf:"bytes,5,opt,name=auto_increment,json=autoIncrement,proto3" json:"auto_increment,omitempty"`
	// The previous name of this object, used to issue RENAME commands instead of DROP/CREATE.
	NamePrevious  string `protobuf:"bytes,6,opt,name=name_previous,json=namePrevious,proto3" json:"name_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_postgres_column_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_column_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_postgres_column_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() *DataType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Column) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *Column) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *Column) GetAutoIncrement() *shared.AutoIncrement {
	if x != nil {
		return x.AutoIncrement
	}
	return nil
}

func (x *Column) GetNamePrevious() string {
	if x != nil {
		return x.NamePrevious
	}
	return ""
}

var File_postgres_column_proto protoreflect.FileDescriptor

const file_postgres_column_proto_rawDesc = "" +
	"\n" +
	"\x15postgres/column.proto\x12\bpostgres\x1a\x18postgres/data_type.proto\x1a core/shared/auto_increment.proto\"\xf2\x01\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\v2\x12.postgres.DataTypeR\x04type\x12\x1f\n" +
	"\vis_nullable\x18\x03 \x01(\bR\n" +
	"isNullable\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12A\n" +
	"\x0eauto_increment\x18\x05 \x01(\v2\x1a.core.shared.AutoIncrementR\rautoIncrement\x12#\n" +
	"\rname_previous\x18\x06 \x01(\tR\fnamePreviousB\x89\x01\n" +
	"\fcom.postgresB\vColumnProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_column_proto_rawDescOnce sync.Once
	file_postgres_column_proto_rawDescData []byte
)

func file_postgres_column_proto_rawDescGZIP() []byte {
	file_postgres_column_proto_rawDescOnce.Do(func() {
		file_postgres_column_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_column_proto_rawDesc), len(file_postgres_column_proto_rawDesc)))
	})
	return file_postgres_column_proto_rawDescData
}

var file_postgres_column_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_column_proto_goTypes = []any{
	(*Column)(nil),               // 0: postgres.Column
	(*DataType)(nil),             // 1: postgres.DataType
	(*shared.AutoIncrement)(nil), // 2: core.shared.AutoIncrement
}
var file_postgres_column_proto_depIdxs = []int32{
	1, // 0: postgres.Column.type:type_name -> postgres.DataType
	2, // 1: postgres.Column.auto_increment:type_name -> core.shared.AutoIncrement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_postgres_column_proto_init() }
func file_postgres_column_proto_init() {
	if File_postgres_column_proto != nil {
		return
	}
	file_postgres_data_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_column_proto_rawDesc), len(file_postgres_column_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_column_proto_goTypes,
		DependencyIndexes: file_postgres_column_proto_depIdxs,
		MessageInfos:      file_postgres_column_proto_msgTypes,
	}.Build()
	File_postgres_column_proto = out.File
	file_postgres_column_proto_goTypes = nil
	file_postgres_column_proto_depIdxs = nil
}
