// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/database.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PostgresDatabase represents the entire structural state of a PostgreSQL
// database cluster or logical database. It holds the collection of specific
// namespaces (schemas) containing all user-defined tables, types, and indexes.
type PostgresDatabase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A collection of logically separated namespaces (schemas) that reside
	// within this PostgreSQL database. Examples include 'public', 'auth',
	// or tenant-specific schema isolation.
	Schemas       []*PostgresSchema `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresDatabase) Reset() {
	*x = PostgresDatabase{}
	mi := &file_postgres_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresDatabase) ProtoMessage() {}

func (x *PostgresDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresDatabase.ProtoReflect.Descriptor instead.
func (*PostgresDatabase) Descriptor() ([]byte, []int) {
	return file_postgres_database_proto_rawDescGZIP(), []int{0}
}

func (x *PostgresDatabase) GetSchemas() []*PostgresSchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

var File_postgres_database_proto protoreflect.FileDescriptor

const file_postgres_database_proto_rawDesc = "" +
	"\n" +
	"\x17postgres/database.proto\x12\bpostgres\x1a\x15postgres/schema.proto\"F\n" +
	"\x10PostgresDatabase\x122\n" +
	"\aschemas\x18\x01 \x03(\v2\x18.postgres.PostgresSchemaR\aschemasB\x8b\x01\n" +
	"\fcom.postgresB\rDatabaseProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_database_proto_rawDescOnce sync.Once
	file_postgres_database_proto_rawDescData []byte
)

func file_postgres_database_proto_rawDescGZIP() []byte {
	file_postgres_database_proto_rawDescOnce.Do(func() {
		file_postgres_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_database_proto_rawDesc), len(file_postgres_database_proto_rawDesc)))
	})
	return file_postgres_database_proto_rawDescData
}

var file_postgres_database_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_database_proto_goTypes = []any{
	(*PostgresDatabase)(nil), // 0: postgres.PostgresDatabase
	(*PostgresSchema)(nil),   // 1: postgres.PostgresSchema
}
var file_postgres_database_proto_depIdxs = []int32{
	1, // 0: postgres.PostgresDatabase.schemas:type_name -> postgres.PostgresSchema
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgres_database_proto_init() }
func file_postgres_database_proto_init() {
	if File_postgres_database_proto != nil {
		return
	}
	file_postgres_schema_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_database_proto_rawDesc), len(file_postgres_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_database_proto_goTypes,
		DependencyIndexes: file_postgres_database_proto_depIdxs,
		MessageInfos:      file_postgres_database_proto_msgTypes,
	}.Build()
	File_postgres_database_proto = out.File
	file_postgres_database_proto_goTypes = nil
	file_postgres_database_proto_depIdxs = nil
}
