// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/empty_payload.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmptyPayload represents a simple "wake up" ping with no data over a channel.
type EmptyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyPayload) Reset() {
	*x = EmptyPayload{}
	mi := &file_postgres_empty_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyPayload) ProtoMessage() {}

func (x *EmptyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_empty_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyPayload.ProtoReflect.Descriptor instead.
func (*EmptyPayload) Descriptor() ([]byte, []int) {
	return file_postgres_empty_payload_proto_rawDescGZIP(), []int{0}
}

var File_postgres_empty_payload_proto protoreflect.FileDescriptor

const file_postgres_empty_payload_proto_rawDesc = "" +
	"\n" +
	"\x1cpostgres/empty_payload.proto\x12\bpostgres\"\x0e\n" +
	"\fEmptyPayloadB\x8f\x01\n" +
	"\fcom.postgresB\x11EmptyPayloadProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_empty_payload_proto_rawDescOnce sync.Once
	file_postgres_empty_payload_proto_rawDescData []byte
)

func file_postgres_empty_payload_proto_rawDescGZIP() []byte {
	file_postgres_empty_payload_proto_rawDescOnce.Do(func() {
		file_postgres_empty_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_empty_payload_proto_rawDesc), len(file_postgres_empty_payload_proto_rawDesc)))
	})
	return file_postgres_empty_payload_proto_rawDescData
}

var file_postgres_empty_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_empty_payload_proto_goTypes = []any{
	(*EmptyPayload)(nil), // 0: postgres.EmptyPayload
}
var file_postgres_empty_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_postgres_empty_payload_proto_init() }
func file_postgres_empty_payload_proto_init() {
	if File_postgres_empty_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_empty_payload_proto_rawDesc), len(file_postgres_empty_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_empty_payload_proto_goTypes,
		DependencyIndexes: file_postgres_empty_payload_proto_depIdxs,
		MessageInfos:      file_postgres_empty_payload_proto_msgTypes,
	}.Build()
	File_postgres_empty_payload_proto = out.File
	file_postgres_empty_payload_proto_goTypes = nil
	file_postgres_empty_payload_proto_depIdxs = nil
}
