// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/function_language.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FunctionLanguage specifies the programming language used for a
// database function.
type FunctionLanguage int32

const (
	// Unspecified language, typically defaults to PLPGSQL in PostgreSQL.
	FunctionLanguage_FUNCTION_LANGUAGE_UNSPECIFIED FunctionLanguage = 0
	// The PL/pgSQL procedural language, native to PostgreSQL.
	FunctionLanguage_FUNCTION_LANGUAGE_PLPGSQL FunctionLanguage = 1
	// Standard SQL query language.
	FunctionLanguage_FUNCTION_LANGUAGE_SQL FunctionLanguage = 2
	// Compiled C language.
	FunctionLanguage_FUNCTION_LANGUAGE_C FunctionLanguage = 3
	// Internal engine language functions (typically written in C and
	// pre-compiled).
	FunctionLanguage_FUNCTION_LANGUAGE_INTERNAL FunctionLanguage = 4
)

// Enum value maps for FunctionLanguage.
var (
	FunctionLanguage_name = map[int32]string{
		0: "FUNCTION_LANGUAGE_UNSPECIFIED",
		1: "FUNCTION_LANGUAGE_PLPGSQL",
		2: "FUNCTION_LANGUAGE_SQL",
		3: "FUNCTION_LANGUAGE_C",
		4: "FUNCTION_LANGUAGE_INTERNAL",
	}
	FunctionLanguage_value = map[string]int32{
		"FUNCTION_LANGUAGE_UNSPECIFIED": 0,
		"FUNCTION_LANGUAGE_PLPGSQL":     1,
		"FUNCTION_LANGUAGE_SQL":         2,
		"FUNCTION_LANGUAGE_C":           3,
		"FUNCTION_LANGUAGE_INTERNAL":    4,
	}
)

func (x FunctionLanguage) Enum() *FunctionLanguage {
	p := new(FunctionLanguage)
	*p = x
	return p
}

func (x FunctionLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_postgres_function_language_proto_enumTypes[0].Descriptor()
}

func (FunctionLanguage) Type() protoreflect.EnumType {
	return &file_postgres_function_language_proto_enumTypes[0]
}

func (x FunctionLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionLanguage.Descriptor instead.
func (FunctionLanguage) EnumDescriptor() ([]byte, []int) {
	return file_postgres_function_language_proto_rawDescGZIP(), []int{0}
}

var File_postgres_function_language_proto protoreflect.FileDescriptor

const file_postgres_function_language_proto_rawDesc = "" +
	"\n" +
	" postgres/function_language.proto\x12\bpostgres*\xa8\x01\n" +
	"\x10FunctionLanguage\x12!\n" +
	"\x1dFUNCTION_LANGUAGE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FUNCTION_LANGUAGE_PLPGSQL\x10\x01\x12\x19\n" +
	"\x15FUNCTION_LANGUAGE_SQL\x10\x02\x12\x17\n" +
	"\x13FUNCTION_LANGUAGE_C\x10\x03\x12\x1e\n" +
	"\x1aFUNCTION_LANGUAGE_INTERNAL\x10\x04B\x93\x01\n" +
	"\fcom.postgresB\x15FunctionLanguageProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_function_language_proto_rawDescOnce sync.Once
	file_postgres_function_language_proto_rawDescData []byte
)

func file_postgres_function_language_proto_rawDescGZIP() []byte {
	file_postgres_function_language_proto_rawDescOnce.Do(func() {
		file_postgres_function_language_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_function_language_proto_rawDesc), len(file_postgres_function_language_proto_rawDesc)))
	})
	return file_postgres_function_language_proto_rawDescData
}

var file_postgres_function_language_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_postgres_function_language_proto_goTypes = []any{
	(FunctionLanguage)(0), // 0: postgres.FunctionLanguage
}
var file_postgres_function_language_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_postgres_function_language_proto_init() }
func file_postgres_function_language_proto_init() {
	if File_postgres_function_language_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_function_language_proto_rawDesc), len(file_postgres_function_language_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_function_language_proto_goTypes,
		DependencyIndexes: file_postgres_function_language_proto_depIdxs,
		EnumInfos:         file_postgres_function_language_proto_enumTypes,
	}.Build()
	File_postgres_function_language_proto = out.File
	file_postgres_function_language_proto_goTypes = nil
	file_postgres_function_language_proto_depIdxs = nil
}
