// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/function.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FunctionDefinition represents a PostgreSQL function or stored procedure.
type FunctionDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique name of the function.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The previous name of this object, used to issue RENAME commands.
	NamePrevious string `protobuf:"bytes,2,opt,name=name_previous,json=namePrevious,proto3" json:"name_previous,omitempty"`
	// The input arguments required by the function.
	Arguments []*FunctionArgument `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// Optional return type. If omitted, implies a 'void' return.
	// Can also be a SETOF or TABLE return type conceptually, but mapped here as a standard DataType.
	ReturnType *DataType `protobuf:"bytes,4,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	// The language the function is written in. Defaults to PLPGSQL if unspecified.
	Language FunctionLanguage `protobuf:"varint,5,opt,name=language,proto3,enum=postgres.FunctionLanguage" json:"language,omitempty"`
	// The raw SQL or PL/pgSQL body of the function.
	Body          string `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_postgres_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_postgres_function_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetNamePrevious() string {
	if x != nil {
		return x.NamePrevious
	}
	return ""
}

func (x *FunctionDefinition) GetArguments() []*FunctionArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *FunctionDefinition) GetReturnType() *DataType {
	if x != nil {
		return x.ReturnType
	}
	return nil
}

func (x *FunctionDefinition) GetLanguage() FunctionLanguage {
	if x != nil {
		return x.Language
	}
	return FunctionLanguage_FUNCTION_LANGUAGE_UNSPECIFIED
}

func (x *FunctionDefinition) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_postgres_function_proto protoreflect.FileDescriptor

const file_postgres_function_proto_rawDesc = "" +
	"\n" +
	"\x17postgres/function.proto\x12\bpostgres\x1a\x18postgres/data_type.proto\x1a postgres/function_language.proto\x1a postgres/function_argument.proto\"\x88\x02\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rname_previous\x18\x02 \x01(\tR\fnamePrevious\x128\n" +
	"\targuments\x18\x03 \x03(\v2\x1a.postgres.FunctionArgumentR\targuments\x123\n" +
	"\vreturn_type\x18\x04 \x01(\v2\x12.postgres.DataTypeR\n" +
	"returnType\x126\n" +
	"\blanguage\x18\x05 \x01(\x0e2\x1a.postgres.FunctionLanguageR\blanguage\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04bodyB\x8b\x01\n" +
	"\fcom.postgresB\rFunctionProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_function_proto_rawDescOnce sync.Once
	file_postgres_function_proto_rawDescData []byte
)

func file_postgres_function_proto_rawDescGZIP() []byte {
	file_postgres_function_proto_rawDescOnce.Do(func() {
		file_postgres_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_function_proto_rawDesc), len(file_postgres_function_proto_rawDesc)))
	})
	return file_postgres_function_proto_rawDescData
}

var file_postgres_function_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_function_proto_goTypes = []any{
	(*FunctionDefinition)(nil), // 0: postgres.FunctionDefinition
	(*FunctionArgument)(nil),   // 1: postgres.FunctionArgument
	(*DataType)(nil),           // 2: postgres.DataType
	(FunctionLanguage)(0),      // 3: postgres.FunctionLanguage
}
var file_postgres_function_proto_depIdxs = []int32{
	1, // 0: postgres.FunctionDefinition.arguments:type_name -> postgres.FunctionArgument
	2, // 1: postgres.FunctionDefinition.return_type:type_name -> postgres.DataType
	3, // 2: postgres.FunctionDefinition.language:type_name -> postgres.FunctionLanguage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_postgres_function_proto_init() }
func file_postgres_function_proto_init() {
	if File_postgres_function_proto != nil {
		return
	}
	file_postgres_data_type_proto_init()
	file_postgres_function_language_proto_init()
	file_postgres_function_argument_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_function_proto_rawDesc), len(file_postgres_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_function_proto_goTypes,
		DependencyIndexes: file_postgres_function_proto_depIdxs,
		MessageInfos:      file_postgres_function_proto_msgTypes,
	}.Build()
	File_postgres_function_proto = out.File
	file_postgres_function_proto_goTypes = nil
	file_postgres_function_proto_depIdxs = nil
}
