// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/function_argument.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FunctionArgument represents an input parameter to a PostgreSQL function.
type FunctionArgument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the function argument.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The data type of the function argument.
	Type          *DataType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionArgument) Reset() {
	*x = FunctionArgument{}
	mi := &file_postgres_function_argument_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionArgument) ProtoMessage() {}

func (x *FunctionArgument) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_function_argument_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionArgument.ProtoReflect.Descriptor instead.
func (*FunctionArgument) Descriptor() ([]byte, []int) {
	return file_postgres_function_argument_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionArgument) GetType() *DataType {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_postgres_function_argument_proto protoreflect.FileDescriptor

const file_postgres_function_argument_proto_rawDesc = "" +
	"\n" +
	" postgres/function_argument.proto\x12\bpostgres\x1a\x18postgres/data_type.proto\"N\n" +
	"\x10FunctionArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\v2\x12.postgres.DataTypeR\x04typeB\x93\x01\n" +
	"\fcom.postgresB\x15FunctionArgumentProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_function_argument_proto_rawDescOnce sync.Once
	file_postgres_function_argument_proto_rawDescData []byte
)

func file_postgres_function_argument_proto_rawDescGZIP() []byte {
	file_postgres_function_argument_proto_rawDescOnce.Do(func() {
		file_postgres_function_argument_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_function_argument_proto_rawDesc), len(file_postgres_function_argument_proto_rawDesc)))
	})
	return file_postgres_function_argument_proto_rawDescData
}

var file_postgres_function_argument_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_function_argument_proto_goTypes = []any{
	(*FunctionArgument)(nil), // 0: postgres.FunctionArgument
	(*DataType)(nil),         // 1: postgres.DataType
}
var file_postgres_function_argument_proto_depIdxs = []int32{
	1, // 0: postgres.FunctionArgument.type:type_name -> postgres.DataType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgres_function_argument_proto_init() }
func file_postgres_function_argument_proto_init() {
	if File_postgres_function_argument_proto != nil {
		return
	}
	file_postgres_data_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_function_argument_proto_rawDesc), len(file_postgres_function_argument_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_function_argument_proto_goTypes,
		DependencyIndexes: file_postgres_function_argument_proto_depIdxs,
		MessageInfos:      file_postgres_function_argument_proto_msgTypes,
	}.Build()
	File_postgres_function_argument_proto = out.File
	file_postgres_function_argument_proto_goTypes = nil
	file_postgres_function_argument_proto_depIdxs = nil
}
