// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/index.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Index represents a database index used to optimize query performance,
// enforce uniqueness, or pre-compute sorting logic.
type Index struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique identifier for the index.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// An ordered list of columns (or expressions) included in the index.
	Columns []*IndexColumn `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// If true, the index enforces a uniqueness constraint, preventing duplicate
	// values across the indexed columns.
	IsUnique bool `protobuf:"varint,3,opt,name=is_unique,json=isUnique,proto3" json:"is_unique,omitempty"`
	// Determines if NULL values are treated as distinct from one another.
	// In PostgreSQL 15+, setting this to true (UNIQUE NULLS NOT DISTINCT) ensures
	// that you cannot have multiple rows with NULL values in the unique index column.
	NullsNotDistinct bool `protobuf:"varint,4,opt,name=nulls_not_distinct,json=nullsNotDistinct,proto3" json:"nulls_not_distinct,omitempty"`
	// The algorithm used for the index (e.g., 'btree', 'hash', 'gin', 'gist').
	// If left empty, the PostgreSQL engine will default to 'btree'.
	AccessMethod string `protobuf:"bytes,5,opt,name=access_method,json=accessMethod,proto3" json:"access_method,omitempty"`
	// A boolean SQL expression that defines a partial index (e.g., 'active = true').
	// Only rows that satisfy this predicate are included in the index structure.
	Predicate string `protobuf:"bytes,6,opt,name=predicate,proto3" json:"predicate,omitempty"`
	// Additional payload columns to append to the index (creating a covering index).
	// These columns aren't used for search/sorting but can be read directly from the
	// index without visiting the underlying table heap.
	IncludeColumns []string `protobuf:"bytes,7,rep,name=include_columns,json=includeColumns,proto3" json:"include_columns,omitempty"`
	// Storage location for the index, if the database utilizes custom tablespaces.
	Tablespace string `protobuf:"bytes,8,opt,name=tablespace,proto3" json:"tablespace,omitempty"`
	// The previous name of this object, used to issue RENAME commands instead of DROP/CREATE.
	NamePrevious  string `protobuf:"bytes,9,opt,name=name_previous,json=namePrevious,proto3" json:"name_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_postgres_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_postgres_index_proto_rawDescGZIP(), []int{0}
}

func (x *Index) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Index) GetColumns() []*IndexColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Index) GetIsUnique() bool {
	if x != nil {
		return x.IsUnique
	}
	return false
}

func (x *Index) GetNullsNotDistinct() bool {
	if x != nil {
		return x.NullsNotDistinct
	}
	return false
}

func (x *Index) GetAccessMethod() string {
	if x != nil {
		return x.AccessMethod
	}
	return ""
}

func (x *Index) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *Index) GetIncludeColumns() []string {
	if x != nil {
		return x.IncludeColumns
	}
	return nil
}

func (x *Index) GetTablespace() string {
	if x != nil {
		return x.Tablespace
	}
	return ""
}

func (x *Index) GetNamePrevious() string {
	if x != nil {
		return x.NamePrevious
	}
	return ""
}

var File_postgres_index_proto protoreflect.FileDescriptor

const file_postgres_index_proto_rawDesc = "" +
	"\n" +
	"\x14postgres/index.proto\x12\bpostgres\x1a\x1bpostgres/index_column.proto\"\xc8\x02\n" +
	"\x05Index\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\acolumns\x18\x02 \x03(\v2\x15.postgres.IndexColumnR\acolumns\x12\x1b\n" +
	"\tis_unique\x18\x03 \x01(\bR\bisUnique\x12,\n" +
	"\x12nulls_not_distinct\x18\x04 \x01(\bR\x10nullsNotDistinct\x12#\n" +
	"\raccess_method\x18\x05 \x01(\tR\faccessMethod\x12\x1c\n" +
	"\tpredicate\x18\x06 \x01(\tR\tpredicate\x12'\n" +
	"\x0finclude_columns\x18\a \x03(\tR\x0eincludeColumns\x12\x1e\n" +
	"\n" +
	"tablespace\x18\b \x01(\tR\n" +
	"tablespace\x12#\n" +
	"\rname_previous\x18\t \x01(\tR\fnamePreviousB\x88\x01\n" +
	"\fcom.postgresB\n" +
	"IndexProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_index_proto_rawDescOnce sync.Once
	file_postgres_index_proto_rawDescData []byte
)

func file_postgres_index_proto_rawDescGZIP() []byte {
	file_postgres_index_proto_rawDescOnce.Do(func() {
		file_postgres_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_index_proto_rawDesc), len(file_postgres_index_proto_rawDesc)))
	})
	return file_postgres_index_proto_rawDescData
}

var file_postgres_index_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_index_proto_goTypes = []any{
	(*Index)(nil),       // 0: postgres.Index
	(*IndexColumn)(nil), // 1: postgres.IndexColumn
}
var file_postgres_index_proto_depIdxs = []int32{
	1, // 0: postgres.Index.columns:type_name -> postgres.IndexColumn
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgres_index_proto_init() }
func file_postgres_index_proto_init() {
	if File_postgres_index_proto != nil {
		return
	}
	file_postgres_index_column_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_index_proto_rawDesc), len(file_postgres_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_index_proto_goTypes,
		DependencyIndexes: file_postgres_index_proto_depIdxs,
		MessageInfos:      file_postgres_index_proto_msgTypes,
	}.Build()
	File_postgres_index_proto = out.File
	file_postgres_index_proto_goTypes = nil
	file_postgres_index_proto_depIdxs = nil
}
