// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/index_access_method.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexAccessMethod specifies the algorithm to be used for a database index.
type IndexAccessMethod int32

const (
	// Unspecified access method, typically defaults to BTREE.
	IndexAccessMethod_INDEX_ACCESS_METHOD_UNSPECIFIED IndexAccessMethod = 0
	// A standard B-Tree index, optimized for equality and range queries.
	IndexAccessMethod_INDEX_ACCESS_METHOD_BTREE IndexAccessMethod = 1
	// A Hash index, optimized strictly for equality comparisons.
	IndexAccessMethod_INDEX_ACCESS_METHOD_HASH IndexAccessMethod = 2
	// A GiST (Generalized Search Tree) index, used for geometric and
	// spatial queries.
	IndexAccessMethod_INDEX_ACCESS_METHOD_GIST IndexAccessMethod = 3
	// An SP-GiST (Space-Partitioned GiST) index, optimized for unbalanced
	// search trees.
	IndexAccessMethod_INDEX_ACCESS_METHOD_SPGIST IndexAccessMethod = 4
	// A GIN (Generalized Inverted Index) index, highly optimized for composite
	// values like arrays and full-text search.
	IndexAccessMethod_INDEX_ACCESS_METHOD_GIN IndexAccessMethod = 5
	// A BRIN (Block Range Index) index, designed for handling very large tables
	// where values correlate with physical block locations.
	IndexAccessMethod_INDEX_ACCESS_METHOD_BRIN IndexAccessMethod = 6
)

// Enum value maps for IndexAccessMethod.
var (
	IndexAccessMethod_name = map[int32]string{
		0: "INDEX_ACCESS_METHOD_UNSPECIFIED",
		1: "INDEX_ACCESS_METHOD_BTREE",
		2: "INDEX_ACCESS_METHOD_HASH",
		3: "INDEX_ACCESS_METHOD_GIST",
		4: "INDEX_ACCESS_METHOD_SPGIST",
		5: "INDEX_ACCESS_METHOD_GIN",
		6: "INDEX_ACCESS_METHOD_BRIN",
	}
	IndexAccessMethod_value = map[string]int32{
		"INDEX_ACCESS_METHOD_UNSPECIFIED": 0,
		"INDEX_ACCESS_METHOD_BTREE":       1,
		"INDEX_ACCESS_METHOD_HASH":        2,
		"INDEX_ACCESS_METHOD_GIST":        3,
		"INDEX_ACCESS_METHOD_SPGIST":      4,
		"INDEX_ACCESS_METHOD_GIN":         5,
		"INDEX_ACCESS_METHOD_BRIN":        6,
	}
)

func (x IndexAccessMethod) Enum() *IndexAccessMethod {
	p := new(IndexAccessMethod)
	*p = x
	return p
}

func (x IndexAccessMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexAccessMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_postgres_index_access_method_proto_enumTypes[0].Descriptor()
}

func (IndexAccessMethod) Type() protoreflect.EnumType {
	return &file_postgres_index_access_method_proto_enumTypes[0]
}

func (x IndexAccessMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexAccessMethod.Descriptor instead.
func (IndexAccessMethod) EnumDescriptor() ([]byte, []int) {
	return file_postgres_index_access_method_proto_rawDescGZIP(), []int{0}
}

var File_postgres_index_access_method_proto protoreflect.FileDescriptor

const file_postgres_index_access_method_proto_rawDesc = "" +
	"\n" +
	"\"postgres/index_access_method.proto\x12\bpostgres*\xee\x01\n" +
	"\x11IndexAccessMethod\x12#\n" +
	"\x1fINDEX_ACCESS_METHOD_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INDEX_ACCESS_METHOD_BTREE\x10\x01\x12\x1c\n" +
	"\x18INDEX_ACCESS_METHOD_HASH\x10\x02\x12\x1c\n" +
	"\x18INDEX_ACCESS_METHOD_GIST\x10\x03\x12\x1e\n" +
	"\x1aINDEX_ACCESS_METHOD_SPGIST\x10\x04\x12\x1b\n" +
	"\x17INDEX_ACCESS_METHOD_GIN\x10\x05\x12\x1c\n" +
	"\x18INDEX_ACCESS_METHOD_BRIN\x10\x06B\x94\x01\n" +
	"\fcom.postgresB\x16IndexAccessMethodProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_index_access_method_proto_rawDescOnce sync.Once
	file_postgres_index_access_method_proto_rawDescData []byte
)

func file_postgres_index_access_method_proto_rawDescGZIP() []byte {
	file_postgres_index_access_method_proto_rawDescOnce.Do(func() {
		file_postgres_index_access_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_index_access_method_proto_rawDesc), len(file_postgres_index_access_method_proto_rawDesc)))
	})
	return file_postgres_index_access_method_proto_rawDescData
}

var file_postgres_index_access_method_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_postgres_index_access_method_proto_goTypes = []any{
	(IndexAccessMethod)(0), // 0: postgres.IndexAccessMethod
}
var file_postgres_index_access_method_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_postgres_index_access_method_proto_init() }
func file_postgres_index_access_method_proto_init() {
	if File_postgres_index_access_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_index_access_method_proto_rawDesc), len(file_postgres_index_access_method_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_index_access_method_proto_goTypes,
		DependencyIndexes: file_postgres_index_access_method_proto_depIdxs,
		EnumInfos:         file_postgres_index_access_method_proto_enumTypes,
	}.Build()
	File_postgres_index_access_method_proto = out.File
	file_postgres_index_access_method_proto_goTypes = nil
	file_postgres_index_access_method_proto_depIdxs = nil
}
