// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/index_column.proto

package postgres

import (
	shared "github.com/uthereal/scheme/genproto/core/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexColumn defines a single column (or expression) and its structural
// configuration within a parent Index.
type IndexColumn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the column (or raw expression) being indexed.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The sorting order of the index column (Ascending, Descending).
	// If unspecified, the engine typically defaults to Ascending.
	Order shared.SortOrder `protobuf:"varint,2,opt,name=order,proto3,enum=core.shared.SortOrder" json:"order,omitempty"`
	// Collation defines the string sorting rules (e.g., 'C', 'en_US.utf8').
	// If left empty, the database's default collation is used.
	Collation string `protobuf:"bytes,3,opt,name=collation,proto3" json:"collation,omitempty"`
	// Operator class defines the strategy the index access method uses
	// (e.g., 'varchar_pattern_ops'). Primarily a PostgreSQL feature for
	// fine-tuning specialized index matching operations.
	OperatorClass string `protobuf:"bytes,4,opt,name=operator_class,json=operatorClass,proto3" json:"operator_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexColumn) Reset() {
	*x = IndexColumn{}
	mi := &file_postgres_index_column_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexColumn) ProtoMessage() {}

func (x *IndexColumn) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_index_column_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexColumn.ProtoReflect.Descriptor instead.
func (*IndexColumn) Descriptor() ([]byte, []int) {
	return file_postgres_index_column_proto_rawDescGZIP(), []int{0}
}

func (x *IndexColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexColumn) GetOrder() shared.SortOrder {
	if x != nil {
		return x.Order
	}
	return shared.SortOrder(0)
}

func (x *IndexColumn) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

func (x *IndexColumn) GetOperatorClass() string {
	if x != nil {
		return x.OperatorClass
	}
	return ""
}

var File_postgres_index_column_proto protoreflect.FileDescriptor

const file_postgres_index_column_proto_rawDesc = "" +
	"\n" +
	"\x1bpostgres/index_column.proto\x12\bpostgres\x1a\x1ccore/shared/sort_order.proto\"\x94\x01\n" +
	"\vIndexColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05order\x18\x02 \x01(\x0e2\x16.core.shared.SortOrderR\x05order\x12\x1c\n" +
	"\tcollation\x18\x03 \x01(\tR\tcollation\x12%\n" +
	"\x0eoperator_class\x18\x04 \x01(\tR\roperatorClassB\x8e\x01\n" +
	"\fcom.postgresB\x10IndexColumnProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_index_column_proto_rawDescOnce sync.Once
	file_postgres_index_column_proto_rawDescData []byte
)

func file_postgres_index_column_proto_rawDescGZIP() []byte {
	file_postgres_index_column_proto_rawDescOnce.Do(func() {
		file_postgres_index_column_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_index_column_proto_rawDesc), len(file_postgres_index_column_proto_rawDesc)))
	})
	return file_postgres_index_column_proto_rawDescData
}

var file_postgres_index_column_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_index_column_proto_goTypes = []any{
	(*IndexColumn)(nil),   // 0: postgres.IndexColumn
	(shared.SortOrder)(0), // 1: core.shared.SortOrder
}
var file_postgres_index_column_proto_depIdxs = []int32{
	1, // 0: postgres.IndexColumn.order:type_name -> core.shared.SortOrder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgres_index_column_proto_init() }
func file_postgres_index_column_proto_init() {
	if File_postgres_index_column_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_index_column_proto_rawDesc), len(file_postgres_index_column_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_index_column_proto_goTypes,
		DependencyIndexes: file_postgres_index_column_proto_depIdxs,
		MessageInfos:      file_postgres_index_column_proto_msgTypes,
	}.Build()
	File_postgres_index_column_proto = out.File
	file_postgres_index_column_proto_goTypes = nil
	file_postgres_index_column_proto_depIdxs = nil
}
