// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/json_payload.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JsonPayload represents a bespoke, strongly-typed JSON object sent over a channel.
type JsonPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The individual fields that compose the JSON payload object.
	Fields        []*JsonPayloadField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonPayload) Reset() {
	*x = JsonPayload{}
	mi := &file_postgres_json_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonPayload) ProtoMessage() {}

func (x *JsonPayload) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_json_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonPayload.ProtoReflect.Descriptor instead.
func (*JsonPayload) Descriptor() ([]byte, []int) {
	return file_postgres_json_payload_proto_rawDescGZIP(), []int{0}
}

func (x *JsonPayload) GetFields() []*JsonPayloadField {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_postgres_json_payload_proto protoreflect.FileDescriptor

const file_postgres_json_payload_proto_rawDesc = "" +
	"\n" +
	"\x1bpostgres/json_payload.proto\x12\bpostgres\x1a!postgres/json_payload_field.proto\"A\n" +
	"\vJsonPayload\x122\n" +
	"\x06fields\x18\x01 \x03(\v2\x1a.postgres.JsonPayloadFieldR\x06fieldsB\x8e\x01\n" +
	"\fcom.postgresB\x10JsonPayloadProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_json_payload_proto_rawDescOnce sync.Once
	file_postgres_json_payload_proto_rawDescData []byte
)

func file_postgres_json_payload_proto_rawDescGZIP() []byte {
	file_postgres_json_payload_proto_rawDescOnce.Do(func() {
		file_postgres_json_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_json_payload_proto_rawDesc), len(file_postgres_json_payload_proto_rawDesc)))
	})
	return file_postgres_json_payload_proto_rawDescData
}

var file_postgres_json_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_json_payload_proto_goTypes = []any{
	(*JsonPayload)(nil),      // 0: postgres.JsonPayload
	(*JsonPayloadField)(nil), // 1: postgres.JsonPayloadField
}
var file_postgres_json_payload_proto_depIdxs = []int32{
	1, // 0: postgres.JsonPayload.fields:type_name -> postgres.JsonPayloadField
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgres_json_payload_proto_init() }
func file_postgres_json_payload_proto_init() {
	if File_postgres_json_payload_proto != nil {
		return
	}
	file_postgres_json_payload_field_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_json_payload_proto_rawDesc), len(file_postgres_json_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_json_payload_proto_goTypes,
		DependencyIndexes: file_postgres_json_payload_proto_depIdxs,
		MessageInfos:      file_postgres_json_payload_proto_msgTypes,
	}.Build()
	File_postgres_json_payload_proto = out.File
	file_postgres_json_payload_proto_goTypes = nil
	file_postgres_json_payload_proto_depIdxs = nil
}
