// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/notification_channel.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationChannel defines a global LISTEN/NOTIFY channel.
type NotificationChannel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The global channel name (e.g., "users_updated").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The previous name of this object, used to issue RENAME commands
	// instead of DROP/CREATE.
	NamePrevious string `protobuf:"bytes,2,opt,name=name_previous,json=namePrevious,proto3" json:"name_previous,omitempty"`
	// Defines exactly what the payload looks like.
	Payload       *NotificationPayload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationChannel) Reset() {
	*x = NotificationChannel{}
	mi := &file_postgres_notification_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationChannel) ProtoMessage() {}

func (x *NotificationChannel) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_notification_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationChannel.ProtoReflect.Descriptor instead.
func (*NotificationChannel) Descriptor() ([]byte, []int) {
	return file_postgres_notification_channel_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotificationChannel) GetNamePrevious() string {
	if x != nil {
		return x.NamePrevious
	}
	return ""
}

func (x *NotificationChannel) GetPayload() *NotificationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_postgres_notification_channel_proto protoreflect.FileDescriptor

const file_postgres_notification_channel_proto_rawDesc = "" +
	"\n" +
	"#postgres/notification_channel.proto\x12\bpostgres\x1a\x18postgres/data_type.proto\x1a#postgres/notification_payload.proto\"\x87\x01\n" +
	"\x13NotificationChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rname_previous\x18\x02 \x01(\tR\fnamePrevious\x127\n" +
	"\apayload\x18\x03 \x01(\v2\x1d.postgres.NotificationPayloadR\apayloadB\x96\x01\n" +
	"\fcom.postgresB\x18NotificationChannelProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_notification_channel_proto_rawDescOnce sync.Once
	file_postgres_notification_channel_proto_rawDescData []byte
)

func file_postgres_notification_channel_proto_rawDescGZIP() []byte {
	file_postgres_notification_channel_proto_rawDescOnce.Do(func() {
		file_postgres_notification_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_notification_channel_proto_rawDesc), len(file_postgres_notification_channel_proto_rawDesc)))
	})
	return file_postgres_notification_channel_proto_rawDescData
}

var file_postgres_notification_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_notification_channel_proto_goTypes = []any{
	(*NotificationChannel)(nil), // 0: postgres.NotificationChannel
	(*NotificationPayload)(nil), // 1: postgres.NotificationPayload
}
var file_postgres_notification_channel_proto_depIdxs = []int32{
	1, // 0: postgres.NotificationChannel.payload:type_name -> postgres.NotificationPayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgres_notification_channel_proto_init() }
func file_postgres_notification_channel_proto_init() {
	if File_postgres_notification_channel_proto != nil {
		return
	}
	file_postgres_data_type_proto_init()
	file_postgres_notification_payload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_notification_channel_proto_rawDesc), len(file_postgres_notification_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_notification_channel_proto_goTypes,
		DependencyIndexes: file_postgres_notification_channel_proto_depIdxs,
		MessageInfos:      file_postgres_notification_channel_proto_msgTypes,
	}.Build()
	File_postgres_notification_channel_proto = out.File
	file_postgres_notification_channel_proto_goTypes = nil
	file_postgres_notification_channel_proto_depIdxs = nil
}
