// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/notify_trigger.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotifyTrigger configures a PostgreSQL trigger that broadcasts event
// notifications to a specified pub/sub channel.
type NotifyTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the trigger function to be generated and attached.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The previous name of this object, used to issue RENAME commands
	// instead of DROP/CREATE.
	NamePrevious string `protobuf:"bytes,2,opt,name=name_previous,json=namePrevious,proto3" json:"name_previous,omitempty"`
	// The global channel to broadcast to. Must exist on the PostgresDatabase.
	Channel string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// The events that fire this trigger (e.g., INSERT, UPDATE).
	Events []TriggerEvent `protobuf:"varint,4,rep,packed,name=events,proto3,enum=postgres.TriggerEvent" json:"events,omitempty"`
	// Specifies whether the trigger fires per row or per statement.
	Orientation   TriggerOrientation `protobuf:"varint,5,opt,name=orientation,proto3,enum=postgres.TriggerOrientation" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyTrigger) Reset() {
	*x = NotifyTrigger{}
	mi := &file_postgres_notify_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTrigger) ProtoMessage() {}

func (x *NotifyTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_notify_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTrigger.ProtoReflect.Descriptor instead.
func (*NotifyTrigger) Descriptor() ([]byte, []int) {
	return file_postgres_notify_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyTrigger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyTrigger) GetNamePrevious() string {
	if x != nil {
		return x.NamePrevious
	}
	return ""
}

func (x *NotifyTrigger) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotifyTrigger) GetEvents() []TriggerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *NotifyTrigger) GetOrientation() TriggerOrientation {
	if x != nil {
		return x.Orientation
	}
	return TriggerOrientation_TRIGGER_ORIENTATION_UNSPECIFIED
}

var File_postgres_notify_trigger_proto protoreflect.FileDescriptor

const file_postgres_notify_trigger_proto_rawDesc = "" +
	"\n" +
	"\x1dpostgres/notify_trigger.proto\x12\bpostgres\x1a\x1cpostgres/trigger_event.proto\x1a\"postgres/trigger_orientation.proto\"\xd2\x01\n" +
	"\rNotifyTrigger\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rname_previous\x18\x02 \x01(\tR\fnamePrevious\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12.\n" +
	"\x06events\x18\x04 \x03(\x0e2\x16.postgres.TriggerEventR\x06events\x12>\n" +
	"\vorientation\x18\x05 \x01(\x0e2\x1c.postgres.TriggerOrientationR\vorientationB\x90\x01\n" +
	"\fcom.postgresB\x12NotifyTriggerProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_notify_trigger_proto_rawDescOnce sync.Once
	file_postgres_notify_trigger_proto_rawDescData []byte
)

func file_postgres_notify_trigger_proto_rawDescGZIP() []byte {
	file_postgres_notify_trigger_proto_rawDescOnce.Do(func() {
		file_postgres_notify_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_notify_trigger_proto_rawDesc), len(file_postgres_notify_trigger_proto_rawDesc)))
	})
	return file_postgres_notify_trigger_proto_rawDescData
}

var file_postgres_notify_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_notify_trigger_proto_goTypes = []any{
	(*NotifyTrigger)(nil),   // 0: postgres.NotifyTrigger
	(TriggerEvent)(0),       // 1: postgres.TriggerEvent
	(TriggerOrientation)(0), // 2: postgres.TriggerOrientation
}
var file_postgres_notify_trigger_proto_depIdxs = []int32{
	1, // 0: postgres.NotifyTrigger.events:type_name -> postgres.TriggerEvent
	2, // 1: postgres.NotifyTrigger.orientation:type_name -> postgres.TriggerOrientation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_postgres_notify_trigger_proto_init() }
func file_postgres_notify_trigger_proto_init() {
	if File_postgres_notify_trigger_proto != nil {
		return
	}
	file_postgres_trigger_event_proto_init()
	file_postgres_trigger_orientation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_notify_trigger_proto_rawDesc), len(file_postgres_notify_trigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_notify_trigger_proto_goTypes,
		DependencyIndexes: file_postgres_notify_trigger_proto_depIdxs,
		MessageInfos:      file_postgres_notify_trigger_proto_msgTypes,
	}.Build()
	File_postgres_notify_trigger_proto = out.File
	file_postgres_notify_trigger_proto_goTypes = nil
	file_postgres_notify_trigger_proto_depIdxs = nil
}
