// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/notification_payload.proto

package postgres

import (
	shared "github.com/uthereal/scheme/genproto/core/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationPayload defines the shape of the data sent over the channel.
type NotificationPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NotificationPayload_Empty
	//	*NotificationPayload_Model
	//	*NotificationPayload_Json
	Payload       isNotificationPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPayload) Reset() {
	*x = NotificationPayload{}
	mi := &file_postgres_notification_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPayload) ProtoMessage() {}

func (x *NotificationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_notification_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPayload.ProtoReflect.Descriptor instead.
func (*NotificationPayload) Descriptor() ([]byte, []int) {
	return file_postgres_notification_payload_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationPayload) GetPayload() isNotificationPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NotificationPayload) GetEmpty() *EmptyPayload {
	if x != nil {
		if x, ok := x.Payload.(*NotificationPayload_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *NotificationPayload) GetModel() *shared.TableReference {
	if x != nil {
		if x, ok := x.Payload.(*NotificationPayload_Model); ok {
			return x.Model
		}
	}
	return nil
}

func (x *NotificationPayload) GetJson() *JsonPayload {
	if x != nil {
		if x, ok := x.Payload.(*NotificationPayload_Json); ok {
			return x.Json
		}
	}
	return nil
}

type isNotificationPayload_Payload interface {
	isNotificationPayload_Payload()
}

type NotificationPayload_Empty struct {
	// An empty payload serving purely as a ping.
	Empty *EmptyPayload `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type NotificationPayload_Model struct {
	// A payload referencing a specific table model layout.
	Model *shared.TableReference `protobuf:"bytes,2,opt,name=model,proto3,oneof"`
}

type NotificationPayload_Json struct {
	// A completely custom JSON payload structure.
	Json *JsonPayload `protobuf:"bytes,3,opt,name=json,proto3,oneof"`
}

func (*NotificationPayload_Empty) isNotificationPayload_Payload() {}

func (*NotificationPayload_Model) isNotificationPayload_Payload() {}

func (*NotificationPayload_Json) isNotificationPayload_Payload() {}

var File_postgres_notification_payload_proto protoreflect.FileDescriptor

const file_postgres_notification_payload_proto_rawDesc = "" +
	"\n" +
	"#postgres/notification_payload.proto\x12\bpostgres\x1a\x18postgres/data_type.proto\x1a!core/shared/table_reference.proto\x1a\x1cpostgres/empty_payload.proto\x1a\x1bpostgres/json_payload.proto\"\xb2\x01\n" +
	"\x13NotificationPayload\x12.\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.postgres.EmptyPayloadH\x00R\x05empty\x123\n" +
	"\x05model\x18\x02 \x01(\v2\x1b.core.shared.TableReferenceH\x00R\x05model\x12+\n" +
	"\x04json\x18\x03 \x01(\v2\x15.postgres.JsonPayloadH\x00R\x04jsonB\t\n" +
	"\apayloadB\x96\x01\n" +
	"\fcom.postgresB\x18NotificationPayloadProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_notification_payload_proto_rawDescOnce sync.Once
	file_postgres_notification_payload_proto_rawDescData []byte
)

func file_postgres_notification_payload_proto_rawDescGZIP() []byte {
	file_postgres_notification_payload_proto_rawDescOnce.Do(func() {
		file_postgres_notification_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_notification_payload_proto_rawDesc), len(file_postgres_notification_payload_proto_rawDesc)))
	})
	return file_postgres_notification_payload_proto_rawDescData
}

var file_postgres_notification_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_notification_payload_proto_goTypes = []any{
	(*NotificationPayload)(nil),   // 0: postgres.NotificationPayload
	(*EmptyPayload)(nil),          // 1: postgres.EmptyPayload
	(*shared.TableReference)(nil), // 2: core.shared.TableReference
	(*JsonPayload)(nil),           // 3: postgres.JsonPayload
}
var file_postgres_notification_payload_proto_depIdxs = []int32{
	1, // 0: postgres.NotificationPayload.empty:type_name -> postgres.EmptyPayload
	2, // 1: postgres.NotificationPayload.model:type_name -> core.shared.TableReference
	3, // 2: postgres.NotificationPayload.json:type_name -> postgres.JsonPayload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_postgres_notification_payload_proto_init() }
func file_postgres_notification_payload_proto_init() {
	if File_postgres_notification_payload_proto != nil {
		return
	}
	file_postgres_data_type_proto_init()
	file_postgres_empty_payload_proto_init()
	file_postgres_json_payload_proto_init()
	file_postgres_notification_payload_proto_msgTypes[0].OneofWrappers = []any{
		(*NotificationPayload_Empty)(nil),
		(*NotificationPayload_Model)(nil),
		(*NotificationPayload_Json)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_notification_payload_proto_rawDesc), len(file_postgres_notification_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_notification_payload_proto_goTypes,
		DependencyIndexes: file_postgres_notification_payload_proto_depIdxs,
		MessageInfos:      file_postgres_notification_payload_proto_msgTypes,
	}.Build()
	File_postgres_notification_payload_proto = out.File
	file_postgres_notification_payload_proto_goTypes = nil
	file_postgres_notification_payload_proto_depIdxs = nil
}
