// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/schema.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PostgresSchema represents a single logical namespace within a PostgreSQL database.
// Schemas are used to organize tables, types, and relations, and to prevent
// naming collisions across different domains of the application.
type PostgresSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique name of the schema namespace (e.g., 'public', 'auth', 'tenant_a').
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The previous name of this object, used to issue RENAME commands instead of DROP/CREATE.
	NamePrevious string `protobuf:"bytes,2,opt,name=name_previous,json=namePrevious,proto3" json:"name_previous,omitempty"`
	// The collection of logical tables contained specifically within this schema namespace.
	Tables []*Table `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"`
	// Schema-level enum type definitions. Enums are created at the schema level
	// and can be referenced by columns within tables in this or other schemas.
	Enums []*EnumDefinition `protobuf:"bytes,4,rep,name=enums,proto3" json:"enums,omitempty"`
	// Schema-level composite type definitions. Composites are created at the schema level
	// and can be referenced by columns within tables in this or other schemas.
	Composites []*CompositeDefinition `protobuf:"bytes,5,rep,name=composites,proto3" json:"composites,omitempty"`
	// Schema-level domain type definitions. Domains are created at the schema level
	// and can be referenced by columns within tables in this or other schemas.
	Domains       []*DomainDefinition `protobuf:"bytes,6,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresSchema) Reset() {
	*x = PostgresSchema{}
	mi := &file_postgres_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresSchema) ProtoMessage() {}

func (x *PostgresSchema) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresSchema.ProtoReflect.Descriptor instead.
func (*PostgresSchema) Descriptor() ([]byte, []int) {
	return file_postgres_schema_proto_rawDescGZIP(), []int{0}
}

func (x *PostgresSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostgresSchema) GetNamePrevious() string {
	if x != nil {
		return x.NamePrevious
	}
	return ""
}

func (x *PostgresSchema) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *PostgresSchema) GetEnums() []*EnumDefinition {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *PostgresSchema) GetComposites() []*CompositeDefinition {
	if x != nil {
		return x.Composites
	}
	return nil
}

func (x *PostgresSchema) GetDomains() []*DomainDefinition {
	if x != nil {
		return x.Domains
	}
	return nil
}

var File_postgres_schema_proto protoreflect.FileDescriptor

const file_postgres_schema_proto_rawDesc = "" +
	"\n" +
	"\x15postgres/schema.proto\x12\bpostgres\x1a\x14postgres/table.proto\x1a\x18postgres/data_type.proto\"\x97\x02\n" +
	"\x0ePostgresSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rname_previous\x18\x02 \x01(\tR\fnamePrevious\x12'\n" +
	"\x06tables\x18\x03 \x03(\v2\x0f.postgres.TableR\x06tables\x12.\n" +
	"\x05enums\x18\x04 \x03(\v2\x18.postgres.EnumDefinitionR\x05enums\x12=\n" +
	"\n" +
	"composites\x18\x05 \x03(\v2\x1d.postgres.CompositeDefinitionR\n" +
	"composites\x124\n" +
	"\adomains\x18\x06 \x03(\v2\x1a.postgres.DomainDefinitionR\adomainsB\x89\x01\n" +
	"\fcom.postgresB\vSchemaProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_schema_proto_rawDescOnce sync.Once
	file_postgres_schema_proto_rawDescData []byte
)

func file_postgres_schema_proto_rawDescGZIP() []byte {
	file_postgres_schema_proto_rawDescOnce.Do(func() {
		file_postgres_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_schema_proto_rawDesc), len(file_postgres_schema_proto_rawDesc)))
	})
	return file_postgres_schema_proto_rawDescData
}

var file_postgres_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_schema_proto_goTypes = []any{
	(*PostgresSchema)(nil),      // 0: postgres.PostgresSchema
	(*Table)(nil),               // 1: postgres.Table
	(*EnumDefinition)(nil),      // 2: postgres.EnumDefinition
	(*CompositeDefinition)(nil), // 3: postgres.CompositeDefinition
	(*DomainDefinition)(nil),    // 4: postgres.DomainDefinition
}
var file_postgres_schema_proto_depIdxs = []int32{
	1, // 0: postgres.PostgresSchema.tables:type_name -> postgres.Table
	2, // 1: postgres.PostgresSchema.enums:type_name -> postgres.EnumDefinition
	3, // 2: postgres.PostgresSchema.composites:type_name -> postgres.CompositeDefinition
	4, // 3: postgres.PostgresSchema.domains:type_name -> postgres.DomainDefinition
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_postgres_schema_proto_init() }
func file_postgres_schema_proto_init() {
	if File_postgres_schema_proto != nil {
		return
	}
	file_postgres_table_proto_init()
	file_postgres_data_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_schema_proto_rawDesc), len(file_postgres_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_schema_proto_goTypes,
		DependencyIndexes: file_postgres_schema_proto_depIdxs,
		MessageInfos:      file_postgres_schema_proto_msgTypes,
	}.Build()
	File_postgres_schema_proto = out.File
	file_postgres_schema_proto_goTypes = nil
	file_postgres_schema_proto_depIdxs = nil
}
