// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/table.proto

package postgres

import (
	shared "github.com/uthereal/scheme/genproto/core/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Table represents a physical database table within a PostgreSQL schema.
// It encapsulates all structural elements, constraints, and relations required
// to fully generate both the database migrations and the ORM code.
type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The physical name of the table as it appears in the database.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The structural columns defined physically within the table.
	Columns []*Column `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// An ordered list of column names that compose the primary key constraint of the table.
	PrimaryKeys []string `protobuf:"bytes,3,rep,name=primary_keys,json=primaryKeys,proto3" json:"primary_keys,omitempty"`
	// Performance indexes applied to the table.
	Indexes []*Index `protobuf:"bytes,4,rep,name=indexes,proto3" json:"indexes,omitempty"`
	// Strictly enforced referential foreign keys linking to other tables.
	ForeignKeys []*shared.ForeignKey `protobuf:"bytes,5,rep,name=foreign_keys,json=foreignKeys,proto3" json:"foreign_keys,omitempty"`
	// Custom check constraints for explicit data validation rules.
	Checks []*CheckConstraint `protobuf:"bytes,6,rep,name=checks,proto3" json:"checks,omitempty"`
	// Derived or computed columns, mapped to GENERATED ALWAYS AS or
	// purely application-level computed fields.
	VirtualColumns []*VirtualColumn `protobuf:"bytes,7,rep,name=virtual_columns,json=virtualColumns,proto3" json:"virtual_columns,omitempty"`
	// Non-enforced relational mappings (virtual foreign keys). Used to instruct
	// the ORM code generator without creating physical database constraints.
	VirtualForeignKeys []*shared.VirtualForeignKey `protobuf:"bytes,8,rep,name=virtual_foreign_keys,json=virtualForeignKeys,proto3" json:"virtual_foreign_keys,omitempty"`
	// Pure relational linkages used exclusively for eager-loading and ORM traversal.
	Relations []*shared.Relation `protobuf:"bytes,9,rep,name=relations,proto3" json:"relations,omitempty"`
	// The previous name of this object, used to issue RENAME commands instead of DROP/CREATE.
	NamePrevious  string `protobuf:"bytes,10,opt,name=name_previous,json=namePrevious,proto3" json:"name_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_postgres_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_postgres_table_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Table) GetPrimaryKeys() []string {
	if x != nil {
		return x.PrimaryKeys
	}
	return nil
}

func (x *Table) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *Table) GetForeignKeys() []*shared.ForeignKey {
	if x != nil {
		return x.ForeignKeys
	}
	return nil
}

func (x *Table) GetChecks() []*CheckConstraint {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *Table) GetVirtualColumns() []*VirtualColumn {
	if x != nil {
		return x.VirtualColumns
	}
	return nil
}

func (x *Table) GetVirtualForeignKeys() []*shared.VirtualForeignKey {
	if x != nil {
		return x.VirtualForeignKeys
	}
	return nil
}

func (x *Table) GetRelations() []*shared.Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *Table) GetNamePrevious() string {
	if x != nil {
		return x.NamePrevious
	}
	return ""
}

var File_postgres_table_proto protoreflect.FileDescriptor

const file_postgres_table_proto_rawDesc = "" +
	"\n" +
	"\x14postgres/table.proto\x12\bpostgres\x1a\x15postgres/column.proto\x1a\x14postgres/index.proto\x1a\x1dcore/shared/foreign_key.proto\x1a\x1fpostgres/check_constraint.proto\x1a\x1dpostgres/virtual_column.proto\x1a%core/shared/virtual_foreign_key.proto\x1a\x1acore/shared/relation.proto\"\xf2\x03\n" +
	"\x05Table\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\acolumns\x18\x02 \x03(\v2\x10.postgres.ColumnR\acolumns\x12!\n" +
	"\fprimary_keys\x18\x03 \x03(\tR\vprimaryKeys\x12)\n" +
	"\aindexes\x18\x04 \x03(\v2\x0f.postgres.IndexR\aindexes\x12:\n" +
	"\fforeign_keys\x18\x05 \x03(\v2\x17.core.shared.ForeignKeyR\vforeignKeys\x121\n" +
	"\x06checks\x18\x06 \x03(\v2\x19.postgres.CheckConstraintR\x06checks\x12@\n" +
	"\x0fvirtual_columns\x18\a \x03(\v2\x17.postgres.VirtualColumnR\x0evirtualColumns\x12P\n" +
	"\x14virtual_foreign_keys\x18\b \x03(\v2\x1e.core.shared.VirtualForeignKeyR\x12virtualForeignKeys\x123\n" +
	"\trelations\x18\t \x03(\v2\x15.core.shared.RelationR\trelations\x12#\n" +
	"\rname_previous\x18\n" +
	" \x01(\tR\fnamePreviousB\x88\x01\n" +
	"\fcom.postgresB\n" +
	"TableProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_table_proto_rawDescOnce sync.Once
	file_postgres_table_proto_rawDescData []byte
)

func file_postgres_table_proto_rawDescGZIP() []byte {
	file_postgres_table_proto_rawDescOnce.Do(func() {
		file_postgres_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_table_proto_rawDesc), len(file_postgres_table_proto_rawDesc)))
	})
	return file_postgres_table_proto_rawDescData
}

var file_postgres_table_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_table_proto_goTypes = []any{
	(*Table)(nil),                    // 0: postgres.Table
	(*Column)(nil),                   // 1: postgres.Column
	(*Index)(nil),                    // 2: postgres.Index
	(*shared.ForeignKey)(nil),        // 3: core.shared.ForeignKey
	(*CheckConstraint)(nil),          // 4: postgres.CheckConstraint
	(*VirtualColumn)(nil),            // 5: postgres.VirtualColumn
	(*shared.VirtualForeignKey)(nil), // 6: core.shared.VirtualForeignKey
	(*shared.Relation)(nil),          // 7: core.shared.Relation
}
var file_postgres_table_proto_depIdxs = []int32{
	1, // 0: postgres.Table.columns:type_name -> postgres.Column
	2, // 1: postgres.Table.indexes:type_name -> postgres.Index
	3, // 2: postgres.Table.foreign_keys:type_name -> core.shared.ForeignKey
	4, // 3: postgres.Table.checks:type_name -> postgres.CheckConstraint
	5, // 4: postgres.Table.virtual_columns:type_name -> postgres.VirtualColumn
	6, // 5: postgres.Table.virtual_foreign_keys:type_name -> core.shared.VirtualForeignKey
	7, // 6: postgres.Table.relations:type_name -> core.shared.Relation
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_postgres_table_proto_init() }
func file_postgres_table_proto_init() {
	if File_postgres_table_proto != nil {
		return
	}
	file_postgres_column_proto_init()
	file_postgres_index_proto_init()
	file_postgres_check_constraint_proto_init()
	file_postgres_virtual_column_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_table_proto_rawDesc), len(file_postgres_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_table_proto_goTypes,
		DependencyIndexes: file_postgres_table_proto_depIdxs,
		MessageInfos:      file_postgres_table_proto_msgTypes,
	}.Build()
	File_postgres_table_proto = out.File
	file_postgres_table_proto_goTypes = nil
	file_postgres_table_proto_depIdxs = nil
}
