// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/table_reference.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModelReference represents a fully qualified reference to a database table.
// It includes the database name, schema name, and table name components
// that together uniquely identify a table in a PostgreSQL database.
type TableReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the postgres database containing the table.
	DatabaseReference string `protobuf:"bytes,1,opt,name=database_reference,json=databaseReference,proto3" json:"database_reference,omitempty"`
	// Name of the postgres schema within the database.
	SchemaReference string `protobuf:"bytes,2,opt,name=schema_reference,json=schemaReference,proto3" json:"schema_reference,omitempty"`
	// Name of the postgres table is the name of the table within the schema.
	TableReference string `protobuf:"bytes,3,opt,name=table_reference,json=tableReference,proto3" json:"table_reference,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TableReference) Reset() {
	*x = TableReference{}
	mi := &file_postgres_table_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableReference) ProtoMessage() {}

func (x *TableReference) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_table_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableReference.ProtoReflect.Descriptor instead.
func (*TableReference) Descriptor() ([]byte, []int) {
	return file_postgres_table_reference_proto_rawDescGZIP(), []int{0}
}

func (x *TableReference) GetDatabaseReference() string {
	if x != nil {
		return x.DatabaseReference
	}
	return ""
}

func (x *TableReference) GetSchemaReference() string {
	if x != nil {
		return x.SchemaReference
	}
	return ""
}

func (x *TableReference) GetTableReference() string {
	if x != nil {
		return x.TableReference
	}
	return ""
}

var File_postgres_table_reference_proto protoreflect.FileDescriptor

const file_postgres_table_reference_proto_rawDesc = "" +
	"\n" +
	"\x1epostgres/table_reference.proto\x12\bpostgres\"\x93\x01\n" +
	"\x0eTableReference\x12-\n" +
	"\x12database_reference\x18\x01 \x01(\tR\x11databaseReference\x12)\n" +
	"\x10schema_reference\x18\x02 \x01(\tR\x0fschemaReference\x12'\n" +
	"\x0ftable_reference\x18\x03 \x01(\tR\x0etableReferenceB\x91\x01\n" +
	"\fcom.postgresB\x13TableReferenceProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_table_reference_proto_rawDescOnce sync.Once
	file_postgres_table_reference_proto_rawDescData []byte
)

func file_postgres_table_reference_proto_rawDescGZIP() []byte {
	file_postgres_table_reference_proto_rawDescOnce.Do(func() {
		file_postgres_table_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_table_reference_proto_rawDesc), len(file_postgres_table_reference_proto_rawDesc)))
	})
	return file_postgres_table_reference_proto_rawDescData
}

var file_postgres_table_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_table_reference_proto_goTypes = []any{
	(*TableReference)(nil), // 0: postgres.TableReference
}
var file_postgres_table_reference_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_postgres_table_reference_proto_init() }
func file_postgres_table_reference_proto_init() {
	if File_postgres_table_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_table_reference_proto_rawDesc), len(file_postgres_table_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_table_reference_proto_goTypes,
		DependencyIndexes: file_postgres_table_reference_proto_depIdxs,
		MessageInfos:      file_postgres_table_reference_proto_msgTypes,
	}.Build()
	File_postgres_table_reference_proto = out.File
	file_postgres_table_reference_proto_goTypes = nil
	file_postgres_table_reference_proto_depIdxs = nil
}
