// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/trigger_event.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TriggerEvent specifies the database operation that causes a trigger to fire.
type TriggerEvent int32

const (
	// Unspecified trigger event.
	TriggerEvent_TRIGGER_EVENT_UNSPECIFIED TriggerEvent = 0
	// The trigger fires upon an INSERT operation.
	TriggerEvent_TRIGGER_EVENT_INSERT TriggerEvent = 1
	// The trigger fires upon an UPDATE operation.
	TriggerEvent_TRIGGER_EVENT_UPDATE TriggerEvent = 2
	// The trigger fires upon a DELETE operation.
	TriggerEvent_TRIGGER_EVENT_DELETE TriggerEvent = 3
	// The trigger fires upon a TRUNCATE operation.
	TriggerEvent_TRIGGER_EVENT_TRUNCATE TriggerEvent = 4
)

// Enum value maps for TriggerEvent.
var (
	TriggerEvent_name = map[int32]string{
		0: "TRIGGER_EVENT_UNSPECIFIED",
		1: "TRIGGER_EVENT_INSERT",
		2: "TRIGGER_EVENT_UPDATE",
		3: "TRIGGER_EVENT_DELETE",
		4: "TRIGGER_EVENT_TRUNCATE",
	}
	TriggerEvent_value = map[string]int32{
		"TRIGGER_EVENT_UNSPECIFIED": 0,
		"TRIGGER_EVENT_INSERT":      1,
		"TRIGGER_EVENT_UPDATE":      2,
		"TRIGGER_EVENT_DELETE":      3,
		"TRIGGER_EVENT_TRUNCATE":    4,
	}
)

func (x TriggerEvent) Enum() *TriggerEvent {
	p := new(TriggerEvent)
	*p = x
	return p
}

func (x TriggerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_postgres_trigger_event_proto_enumTypes[0].Descriptor()
}

func (TriggerEvent) Type() protoreflect.EnumType {
	return &file_postgres_trigger_event_proto_enumTypes[0]
}

func (x TriggerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerEvent.Descriptor instead.
func (TriggerEvent) EnumDescriptor() ([]byte, []int) {
	return file_postgres_trigger_event_proto_rawDescGZIP(), []int{0}
}

var File_postgres_trigger_event_proto protoreflect.FileDescriptor

const file_postgres_trigger_event_proto_rawDesc = "" +
	"\n" +
	"\x1cpostgres/trigger_event.proto\x12\bpostgres*\x97\x01\n" +
	"\fTriggerEvent\x12\x1d\n" +
	"\x19TRIGGER_EVENT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRIGGER_EVENT_INSERT\x10\x01\x12\x18\n" +
	"\x14TRIGGER_EVENT_UPDATE\x10\x02\x12\x18\n" +
	"\x14TRIGGER_EVENT_DELETE\x10\x03\x12\x1a\n" +
	"\x16TRIGGER_EVENT_TRUNCATE\x10\x04B\x8f\x01\n" +
	"\fcom.postgresB\x11TriggerEventProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_trigger_event_proto_rawDescOnce sync.Once
	file_postgres_trigger_event_proto_rawDescData []byte
)

func file_postgres_trigger_event_proto_rawDescGZIP() []byte {
	file_postgres_trigger_event_proto_rawDescOnce.Do(func() {
		file_postgres_trigger_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_trigger_event_proto_rawDesc), len(file_postgres_trigger_event_proto_rawDesc)))
	})
	return file_postgres_trigger_event_proto_rawDescData
}

var file_postgres_trigger_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_postgres_trigger_event_proto_goTypes = []any{
	(TriggerEvent)(0), // 0: postgres.TriggerEvent
}
var file_postgres_trigger_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_postgres_trigger_event_proto_init() }
func file_postgres_trigger_event_proto_init() {
	if File_postgres_trigger_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_trigger_event_proto_rawDesc), len(file_postgres_trigger_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_trigger_event_proto_goTypes,
		DependencyIndexes: file_postgres_trigger_event_proto_depIdxs,
		EnumInfos:         file_postgres_trigger_event_proto_enumTypes,
	}.Build()
	File_postgres_trigger_event_proto = out.File
	file_postgres_trigger_event_proto_goTypes = nil
	file_postgres_trigger_event_proto_depIdxs = nil
}
