// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: postgres/trigger_orientation.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TriggerOrientation specifies whether a trigger fires once per statement
// or once per modified row.
type TriggerOrientation int32

const (
	// Unspecified trigger orientation.
	TriggerOrientation_TRIGGER_ORIENTATION_UNSPECIFIED TriggerOrientation = 0
	// The trigger fires once for every row affected by the operation.
	TriggerOrientation_TRIGGER_ORIENTATION_ROW TriggerOrientation = 1
	// The trigger fires once for the entire statement, regardless of rows
	// affected.
	TriggerOrientation_TRIGGER_ORIENTATION_STATEMENT TriggerOrientation = 2
)

// Enum value maps for TriggerOrientation.
var (
	TriggerOrientation_name = map[int32]string{
		0: "TRIGGER_ORIENTATION_UNSPECIFIED",
		1: "TRIGGER_ORIENTATION_ROW",
		2: "TRIGGER_ORIENTATION_STATEMENT",
	}
	TriggerOrientation_value = map[string]int32{
		"TRIGGER_ORIENTATION_UNSPECIFIED": 0,
		"TRIGGER_ORIENTATION_ROW":         1,
		"TRIGGER_ORIENTATION_STATEMENT":   2,
	}
)

func (x TriggerOrientation) Enum() *TriggerOrientation {
	p := new(TriggerOrientation)
	*p = x
	return p
}

func (x TriggerOrientation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerOrientation) Descriptor() protoreflect.EnumDescriptor {
	return file_postgres_trigger_orientation_proto_enumTypes[0].Descriptor()
}

func (TriggerOrientation) Type() protoreflect.EnumType {
	return &file_postgres_trigger_orientation_proto_enumTypes[0]
}

func (x TriggerOrientation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerOrientation.Descriptor instead.
func (TriggerOrientation) EnumDescriptor() ([]byte, []int) {
	return file_postgres_trigger_orientation_proto_rawDescGZIP(), []int{0}
}

var File_postgres_trigger_orientation_proto protoreflect.FileDescriptor

const file_postgres_trigger_orientation_proto_rawDesc = "" +
	"\n" +
	"\"postgres/trigger_orientation.proto\x12\bpostgres*y\n" +
	"\x12TriggerOrientation\x12#\n" +
	"\x1fTRIGGER_ORIENTATION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRIGGER_ORIENTATION_ROW\x10\x01\x12!\n" +
	"\x1dTRIGGER_ORIENTATION_STATEMENT\x10\x02B\x95\x01\n" +
	"\fcom.postgresB\x17TriggerOrientationProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_trigger_orientation_proto_rawDescOnce sync.Once
	file_postgres_trigger_orientation_proto_rawDescData []byte
)

func file_postgres_trigger_orientation_proto_rawDescGZIP() []byte {
	file_postgres_trigger_orientation_proto_rawDescOnce.Do(func() {
		file_postgres_trigger_orientation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_trigger_orientation_proto_rawDesc), len(file_postgres_trigger_orientation_proto_rawDesc)))
	})
	return file_postgres_trigger_orientation_proto_rawDescData
}

var file_postgres_trigger_orientation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_postgres_trigger_orientation_proto_goTypes = []any{
	(TriggerOrientation)(0), // 0: postgres.TriggerOrientation
}
var file_postgres_trigger_orientation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_postgres_trigger_orientation_proto_init() }
func file_postgres_trigger_orientation_proto_init() {
	if File_postgres_trigger_orientation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_trigger_orientation_proto_rawDesc), len(file_postgres_trigger_orientation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_trigger_orientation_proto_goTypes,
		DependencyIndexes: file_postgres_trigger_orientation_proto_depIdxs,
		EnumInfos:         file_postgres_trigger_orientation_proto_enumTypes,
	}.Build()
	File_postgres_trigger_orientation_proto = out.File
	file_postgres_trigger_orientation_proto_goTypes = nil
	file_postgres_trigger_orientation_proto_depIdxs = nil
}
