// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: postgres/virtual_column.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VirtualColumn represents a column whose value is derived or computed,
// rather than being physically stored like a standard column.
// This maps to physical PostgreSQL `GENERATED ALWAYS AS (...)` columns,
// or purely application-level computed properties.
type VirtualColumn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the virtual column.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The expected structural data type of the computed result.
	Type *DataType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// The SQL expression used to compute the column's value
	// (e.g., 'first_name || " " || last_name').
	Expression    string `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualColumn) Reset() {
	*x = VirtualColumn{}
	mi := &file_postgres_virtual_column_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualColumn) ProtoMessage() {}

func (x *VirtualColumn) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_virtual_column_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualColumn.ProtoReflect.Descriptor instead.
func (*VirtualColumn) Descriptor() ([]byte, []int) {
	return file_postgres_virtual_column_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualColumn) GetType() *DataType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *VirtualColumn) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

var File_postgres_virtual_column_proto protoreflect.FileDescriptor

const file_postgres_virtual_column_proto_rawDesc = "" +
	"\n" +
	"\x1dpostgres/virtual_column.proto\x12\bpostgres\x1a\x18postgres/data_type.proto\"k\n" +
	"\rVirtualColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\v2\x12.postgres.DataTypeR\x04type\x12\x1e\n" +
	"\n" +
	"expression\x18\x03 \x01(\tR\n" +
	"expressionB\x90\x01\n" +
	"\fcom.postgresB\x12VirtualColumnProtoP\x01Z,github.com/uthereal/scheme/genproto/postgres\xa2\x02\x03PXX\xaa\x02\bPostgres\xca\x02\bPostgres\xe2\x02\x14Postgres\\GPBMetadata\xea\x02\bPostgresb\x06proto3"

var (
	file_postgres_virtual_column_proto_rawDescOnce sync.Once
	file_postgres_virtual_column_proto_rawDescData []byte
)

func file_postgres_virtual_column_proto_rawDescGZIP() []byte {
	file_postgres_virtual_column_proto_rawDescOnce.Do(func() {
		file_postgres_virtual_column_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_postgres_virtual_column_proto_rawDesc), len(file_postgres_virtual_column_proto_rawDesc)))
	})
	return file_postgres_virtual_column_proto_rawDescData
}

var file_postgres_virtual_column_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_postgres_virtual_column_proto_goTypes = []any{
	(*VirtualColumn)(nil), // 0: postgres.VirtualColumn
	(*DataType)(nil),      // 1: postgres.DataType
}
var file_postgres_virtual_column_proto_depIdxs = []int32{
	1, // 0: postgres.VirtualColumn.type:type_name -> postgres.DataType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgres_virtual_column_proto_init() }
func file_postgres_virtual_column_proto_init() {
	if File_postgres_virtual_column_proto != nil {
		return
	}
	file_postgres_data_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_postgres_virtual_column_proto_rawDesc), len(file_postgres_virtual_column_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_virtual_column_proto_goTypes,
		DependencyIndexes: file_postgres_virtual_column_proto_depIdxs,
		MessageInfos:      file_postgres_virtual_column_proto_msgTypes,
	}.Build()
	File_postgres_virtual_column_proto = out.File
	file_postgres_virtual_column_proto_goTypes = nil
	file_postgres_virtual_column_proto_depIdxs = nil
}
